package com.mimp.bean;
// Generated Dec 23, 2013 10:39:27 AM by Hibernate Tools 3.6.0



/**
 * AsistenciaFT generated by hbm2java
 */
public class AsistenciaFT  implements java.io.Serializable {


     private long idasistenciaFT;
     private FormularioSesion formularioSesion;
     private Turno turno;
     private Character asistencia;
     private Short inasJus;

    public AsistenciaFT() {
    }

	
    public AsistenciaFT(long idasistenciaFT, FormularioSesion formularioSesion, Turno turno) {
        this.idasistenciaFT = idasistenciaFT;
        this.formularioSesion = formularioSesion;
        this.turno = turno;
    }
    public AsistenciaFT(long idasistenciaFT, FormularioSesion formularioSesion, Turno turno, Character asistencia, Short inasJus) {
       this.idasistenciaFT = idasistenciaFT;
       this.formularioSesion = formularioSesion;
       this.turno = turno;
       this.asistencia = asistencia;
       this.inasJus = inasJus;
    }
   
    public long getIdasistenciaFT() {
        return this.idasistenciaFT;
    }
    
    public void setIdasistenciaFT(long idasistenciaFT) {
        this.idasistenciaFT = idasistenciaFT;
    }
    public FormularioSesion getFormularioSesion() {
        return this.formularioSesion;
    }
    
    public void setFormularioSesion(FormularioSesion formularioSesion) {
        this.formularioSesion = formularioSesion;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Character getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Character asistencia) {
        this.asistencia = asistencia;
    }
    public Short getInasJus() {
        return this.inasJus;
    }
    
    public void setInasJus(Short inasJus) {
        this.inasJus = inasJus;
    }




}


