package com.mimp.bean;
// Generated Dec 12, 2013 4:23:07 PM by Hibernate Tools 3.6.0



/**
 * AsistenciaFR generated by hbm2java
 */
public class AsistenciaFR  implements java.io.Serializable {


     private long idasistenciaFR;
     private Familia familia;
     private Reunion reunion;
     private Character asistencia;
     private Short inasJus;

    public AsistenciaFR() {
    }

	
    public AsistenciaFR(long idasistenciaFR, Familia familia, Reunion reunion) {
        this.idasistenciaFR = idasistenciaFR;
        this.familia = familia;
        this.reunion = reunion;
    }
    public AsistenciaFR(long idasistenciaFR, Familia familia, Reunion reunion, Character asistencia, Short inasJus) {
       this.idasistenciaFR = idasistenciaFR;
       this.familia = familia;
       this.reunion = reunion;
       this.asistencia = asistencia;
       this.inasJus = inasJus;
    }
   
    public long getIdasistenciaFR() {
        return this.idasistenciaFR;
    }
    
    public void setIdasistenciaFR(long idasistenciaFR) {
        this.idasistenciaFR = idasistenciaFR;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public Reunion getReunion() {
        return this.reunion;
    }
    
    public void setReunion(Reunion reunion) {
        this.reunion = reunion;
    }
    public Character getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Character asistencia) {
        this.asistencia = asistencia;
    }
    public Short getInasJus() {
        return this.inasJus;
    }
    
    public void setInasJus(Short inasJus) {
        this.inasJus = inasJus;
    }




}


