package com.mimp.bean;
// Generated 6/12/2013 11:57:53 AM by Hibernate Tools 3.6.0



/**
 * AsistenciaFR generated by hbm2java
 */
public class AsistenciaFR  implements java.io.Serializable {


     private Integer idasistenciaFR;
     private Familia familia;
     private Reunion reunion;
     private Character asistencia;
     private Boolean inasJus;

    public AsistenciaFR() {
    }

	
    public AsistenciaFR(Familia familia, Reunion reunion) {
        this.familia = familia;
        this.reunion = reunion;
    }
    public AsistenciaFR(Familia familia, Reunion reunion, Character asistencia, Boolean inasJus) {
       this.familia = familia;
       this.reunion = reunion;
       this.asistencia = asistencia;
       this.inasJus = inasJus;
    }
   
    public Integer getIdasistenciaFR() {
        return this.idasistenciaFR;
    }
    
    public void setIdasistenciaFR(Integer idasistenciaFR) {
        this.idasistenciaFR = idasistenciaFR;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public Reunion getReunion() {
        return this.reunion;
    }
    
    public void setReunion(Reunion reunion) {
        this.reunion = reunion;
    }
    public Character getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Character asistencia) {
        this.asistencia = asistencia;
    }
    public Boolean getInasJus() {
        return this.inasJus;
    }
    
    public void setInasJus(Boolean inasJus) {
        this.inasJus = inasJus;
    }




}


