package com.mimp.bean;
// Generated Dec 10, 2013 11:15:19 AM by Hibernate Tools 3.6.0



/**
 * Autoridad generated by hbm2java
 */
public class Autoridad  implements java.io.Serializable {


     private Integer idautoridad;
     private Entidad entidad;
     private String tipo;
     private String user;
     private String pass;

    public Autoridad() {
    }

	
    public Autoridad(Entidad entidad) {
        this.entidad = entidad;
    }
    public Autoridad(Entidad entidad, String tipo, String user, String pass) {
       this.entidad = entidad;
       this.tipo = tipo;
       this.user = user;
       this.pass = pass;
    }
   
    public Integer getIdautoridad() {
        return this.idautoridad;
    }
    
    public void setIdautoridad(Integer idautoridad) {
        this.idautoridad = idautoridad;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


