package com.mimp.bean;
// Generated 10/12/2013 03:07:34 PM by Hibernate Tools 3.6.0



/**
 * Autoridad generated by hbm2java
 */
public class Autoridad  implements java.io.Serializable {


     private Integer idautoridad;
     private Entidad entidad;
     private String tipo;

    public Autoridad() {
    }

	
    public Autoridad(Entidad entidad) {
        this.entidad = entidad;
    }
    public Autoridad(Entidad entidad, String tipo) {
       this.entidad = entidad;
       this.tipo = tipo;
    }
   
    public Integer getIdautoridad() {
        return this.idautoridad;
    }
    
    public void setIdautoridad(Integer idautoridad) {
        this.idautoridad = idautoridad;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


