package com.mimp.bean;
// Generated Nov 22, 2013 4:14:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Designacion generated by hbm2java
 */
public class Designacion  implements java.io.Serializable {


     private Integer iddesignacion;
     private Nna nna;
     private ExpedienteFamilia expedienteFamilia;
     private String NDesignacion;
     private Integer prioridad;
     private Date fechaPropuesta;
     private Date fechaConsejo;
     private String tipoPropuesta;
     private String obs;

    public Designacion() {
    }

	
    public Designacion(Nna nna, ExpedienteFamilia expedienteFamilia) {
        this.nna = nna;
        this.expedienteFamilia = expedienteFamilia;
    }
    public Designacion(Nna nna, ExpedienteFamilia expedienteFamilia, String NDesignacion, Integer prioridad, Date fechaPropuesta, Date fechaConsejo, String tipoPropuesta, String obs) {
       this.nna = nna;
       this.expedienteFamilia = expedienteFamilia;
       this.NDesignacion = NDesignacion;
       this.prioridad = prioridad;
       this.fechaPropuesta = fechaPropuesta;
       this.fechaConsejo = fechaConsejo;
       this.tipoPropuesta = tipoPropuesta;
       this.obs = obs;
    }
   
    public Integer getIddesignacion() {
        return this.iddesignacion;
    }
    
    public void setIddesignacion(Integer iddesignacion) {
        this.iddesignacion = iddesignacion;
    }
    public Nna getNna() {
        return this.nna;
    }
    
    public void setNna(Nna nna) {
        this.nna = nna;
    }
    public ExpedienteFamilia getExpedienteFamilia() {
        return this.expedienteFamilia;
    }
    
    public void setExpedienteFamilia(ExpedienteFamilia expedienteFamilia) {
        this.expedienteFamilia = expedienteFamilia;
    }
    public String getNDesignacion() {
        return this.NDesignacion;
    }
    
    public void setNDesignacion(String NDesignacion) {
        this.NDesignacion = NDesignacion;
    }
    public Integer getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Integer prioridad) {
        this.prioridad = prioridad;
    }
    public Date getFechaPropuesta() {
        return this.fechaPropuesta;
    }
    
    public void setFechaPropuesta(Date fechaPropuesta) {
        this.fechaPropuesta = fechaPropuesta;
    }
    public Date getFechaConsejo() {
        return this.fechaConsejo;
    }
    
    public void setFechaConsejo(Date fechaConsejo) {
        this.fechaConsejo = fechaConsejo;
    }
    public String getTipoPropuesta() {
        return this.tipoPropuesta;
    }
    
    public void setTipoPropuesta(String tipoPropuesta) {
        this.tipoPropuesta = tipoPropuesta;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }




}


