package com.mimp.bean;
// Generated Dec 23, 2013 10:39:27 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Designacion generated by hbm2java
 */
public class Designacion  implements java.io.Serializable {


     private long iddesignacion;
     private Nna nna;
     private Personal personal;
     private ExpedienteFamilia expedienteFamilia;
     private Long NDesignacion;
     private Long prioridad;
     private Date fechaPropuesta;
     private Date fechaConsejo;
     private Short aceptacionConsejo;
     private String tipoPropuesta;
     private String obs;

    public Designacion() {
    }

	
    public Designacion(long iddesignacion, Nna nna, Personal personal, ExpedienteFamilia expedienteFamilia) {
        this.iddesignacion = iddesignacion;
        this.nna = nna;
        this.personal = personal;
        this.expedienteFamilia = expedienteFamilia;
    }
    public Designacion(long iddesignacion, Nna nna, Personal personal, ExpedienteFamilia expedienteFamilia, Long NDesignacion, Long prioridad, Date fechaPropuesta, Date fechaConsejo, Short aceptacionConsejo, String tipoPropuesta, String obs) {
       this.iddesignacion = iddesignacion;
       this.nna = nna;
       this.personal = personal;
       this.expedienteFamilia = expedienteFamilia;
       this.NDesignacion = NDesignacion;
       this.prioridad = prioridad;
       this.fechaPropuesta = fechaPropuesta;
       this.fechaConsejo = fechaConsejo;
       this.aceptacionConsejo = aceptacionConsejo;
       this.tipoPropuesta = tipoPropuesta;
       this.obs = obs;
    }
   
    public long getIddesignacion() {
        return this.iddesignacion;
    }
    
    public void setIddesignacion(long iddesignacion) {
        this.iddesignacion = iddesignacion;
    }
    public Nna getNna() {
        return this.nna;
    }
    
    public void setNna(Nna nna) {
        this.nna = nna;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public ExpedienteFamilia getExpedienteFamilia() {
        return this.expedienteFamilia;
    }
    
    public void setExpedienteFamilia(ExpedienteFamilia expedienteFamilia) {
        this.expedienteFamilia = expedienteFamilia;
    }
    public Long getNDesignacion() {
        return this.NDesignacion;
    }
    
    public void setNDesignacion(Long NDesignacion) {
        this.NDesignacion = NDesignacion;
    }
    public Long getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Long prioridad) {
        this.prioridad = prioridad;
    }
    public Date getFechaPropuesta() {
        return this.fechaPropuesta;
    }
    
    public void setFechaPropuesta(Date fechaPropuesta) {
        this.fechaPropuesta = fechaPropuesta;
    }
    public Date getFechaConsejo() {
        return this.fechaConsejo;
    }
    
    public void setFechaConsejo(Date fechaConsejo) {
        this.fechaConsejo = fechaConsejo;
    }
    public Short getAceptacionConsejo() {
        return this.aceptacionConsejo;
    }
    
    public void setAceptacionConsejo(Short aceptacionConsejo) {
        this.aceptacionConsejo = aceptacionConsejo;
    }
    public String getTipoPropuesta() {
        return this.tipoPropuesta;
    }
    
    public void setTipoPropuesta(String tipoPropuesta) {
        this.tipoPropuesta = tipoPropuesta;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }




}


