package com.mimp.bean;
// Generated Dec 23, 2013 3:56:21 PM by Hibernate Tools 3.6.0



/**
 * EvalLegal generated by hbm2java
 */
public class EvalLegal  implements java.io.Serializable {


     private long idevalLegal;
     private Evaluacion evaluacion;
     private Short solicitudDga;
     private String solicitudDgaObs;
     private Short evalSocial;
     private String evalSocialObs;
     private Short evalPsicologica;
     private String evalPsicologicaObs;
     private Short certDomiciliario;
     private String certDomiciliarioObs;
     private Short partidaMatrimonio;
     private String partidaMatrimonioObs;
     private Short sentenciaDivorcio;
     private String sentenciaDivorcioObs;
     private Short partDefuncCony;
     private String partDefuncConyObs;
     private Short partNacHijBio;
     private String partNacHijBioObs;
     private Short partNacHijAdop;
     private String partNacHijAdopObs;
     private Short reportSegPostAdopDga;
     private String reportSegPostAdopDgaObs;
     private Short fotografiaAdopHogar;
     private String fotografiaAdopHogarObs;
     private Short compromisoPostAdop;
     private String compromisoPostAdopObs;

    public EvalLegal() {
    }

	
    public EvalLegal(long idevalLegal, Evaluacion evaluacion) {
        this.idevalLegal = idevalLegal;
        this.evaluacion = evaluacion;
    }
    public EvalLegal(long idevalLegal, Evaluacion evaluacion, Short solicitudDga, String solicitudDgaObs, Short evalSocial, String evalSocialObs, Short evalPsicologica, String evalPsicologicaObs, Short certDomiciliario, String certDomiciliarioObs, Short partidaMatrimonio, String partidaMatrimonioObs, Short sentenciaDivorcio, String sentenciaDivorcioObs, Short partDefuncCony, String partDefuncConyObs, Short partNacHijBio, String partNacHijBioObs, Short partNacHijAdop, String partNacHijAdopObs, Short reportSegPostAdopDga, String reportSegPostAdopDgaObs, Short fotografiaAdopHogar, String fotografiaAdopHogarObs, Short compromisoPostAdop, String compromisoPostAdopObs) {
       this.idevalLegal = idevalLegal;
       this.evaluacion = evaluacion;
       this.solicitudDga = solicitudDga;
       this.solicitudDgaObs = solicitudDgaObs;
       this.evalSocial = evalSocial;
       this.evalSocialObs = evalSocialObs;
       this.evalPsicologica = evalPsicologica;
       this.evalPsicologicaObs = evalPsicologicaObs;
       this.certDomiciliario = certDomiciliario;
       this.certDomiciliarioObs = certDomiciliarioObs;
       this.partidaMatrimonio = partidaMatrimonio;
       this.partidaMatrimonioObs = partidaMatrimonioObs;
       this.sentenciaDivorcio = sentenciaDivorcio;
       this.sentenciaDivorcioObs = sentenciaDivorcioObs;
       this.partDefuncCony = partDefuncCony;
       this.partDefuncConyObs = partDefuncConyObs;
       this.partNacHijBio = partNacHijBio;
       this.partNacHijBioObs = partNacHijBioObs;
       this.partNacHijAdop = partNacHijAdop;
       this.partNacHijAdopObs = partNacHijAdopObs;
       this.reportSegPostAdopDga = reportSegPostAdopDga;
       this.reportSegPostAdopDgaObs = reportSegPostAdopDgaObs;
       this.fotografiaAdopHogar = fotografiaAdopHogar;
       this.fotografiaAdopHogarObs = fotografiaAdopHogarObs;
       this.compromisoPostAdop = compromisoPostAdop;
       this.compromisoPostAdopObs = compromisoPostAdopObs;
    }
   
    public long getIdevalLegal() {
        return this.idevalLegal;
    }
    
    public void setIdevalLegal(long idevalLegal) {
        this.idevalLegal = idevalLegal;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Short getSolicitudDga() {
        return this.solicitudDga;
    }
    
    public void setSolicitudDga(Short solicitudDga) {
        this.solicitudDga = solicitudDga;
    }
    public String getSolicitudDgaObs() {
        return this.solicitudDgaObs;
    }
    
    public void setSolicitudDgaObs(String solicitudDgaObs) {
        this.solicitudDgaObs = solicitudDgaObs;
    }
    public Short getEvalSocial() {
        return this.evalSocial;
    }
    
    public void setEvalSocial(Short evalSocial) {
        this.evalSocial = evalSocial;
    }
    public String getEvalSocialObs() {
        return this.evalSocialObs;
    }
    
    public void setEvalSocialObs(String evalSocialObs) {
        this.evalSocialObs = evalSocialObs;
    }
    public Short getEvalPsicologica() {
        return this.evalPsicologica;
    }
    
    public void setEvalPsicologica(Short evalPsicologica) {
        this.evalPsicologica = evalPsicologica;
    }
    public String getEvalPsicologicaObs() {
        return this.evalPsicologicaObs;
    }
    
    public void setEvalPsicologicaObs(String evalPsicologicaObs) {
        this.evalPsicologicaObs = evalPsicologicaObs;
    }
    public Short getCertDomiciliario() {
        return this.certDomiciliario;
    }
    
    public void setCertDomiciliario(Short certDomiciliario) {
        this.certDomiciliario = certDomiciliario;
    }
    public String getCertDomiciliarioObs() {
        return this.certDomiciliarioObs;
    }
    
    public void setCertDomiciliarioObs(String certDomiciliarioObs) {
        this.certDomiciliarioObs = certDomiciliarioObs;
    }
    public Short getPartidaMatrimonio() {
        return this.partidaMatrimonio;
    }
    
    public void setPartidaMatrimonio(Short partidaMatrimonio) {
        this.partidaMatrimonio = partidaMatrimonio;
    }
    public String getPartidaMatrimonioObs() {
        return this.partidaMatrimonioObs;
    }
    
    public void setPartidaMatrimonioObs(String partidaMatrimonioObs) {
        this.partidaMatrimonioObs = partidaMatrimonioObs;
    }
    public Short getSentenciaDivorcio() {
        return this.sentenciaDivorcio;
    }
    
    public void setSentenciaDivorcio(Short sentenciaDivorcio) {
        this.sentenciaDivorcio = sentenciaDivorcio;
    }
    public String getSentenciaDivorcioObs() {
        return this.sentenciaDivorcioObs;
    }
    
    public void setSentenciaDivorcioObs(String sentenciaDivorcioObs) {
        this.sentenciaDivorcioObs = sentenciaDivorcioObs;
    }
    public Short getPartDefuncCony() {
        return this.partDefuncCony;
    }
    
    public void setPartDefuncCony(Short partDefuncCony) {
        this.partDefuncCony = partDefuncCony;
    }
    public String getPartDefuncConyObs() {
        return this.partDefuncConyObs;
    }
    
    public void setPartDefuncConyObs(String partDefuncConyObs) {
        this.partDefuncConyObs = partDefuncConyObs;
    }
    public Short getPartNacHijBio() {
        return this.partNacHijBio;
    }
    
    public void setPartNacHijBio(Short partNacHijBio) {
        this.partNacHijBio = partNacHijBio;
    }
    public String getPartNacHijBioObs() {
        return this.partNacHijBioObs;
    }
    
    public void setPartNacHijBioObs(String partNacHijBioObs) {
        this.partNacHijBioObs = partNacHijBioObs;
    }
    public Short getPartNacHijAdop() {
        return this.partNacHijAdop;
    }
    
    public void setPartNacHijAdop(Short partNacHijAdop) {
        this.partNacHijAdop = partNacHijAdop;
    }
    public String getPartNacHijAdopObs() {
        return this.partNacHijAdopObs;
    }
    
    public void setPartNacHijAdopObs(String partNacHijAdopObs) {
        this.partNacHijAdopObs = partNacHijAdopObs;
    }
    public Short getReportSegPostAdopDga() {
        return this.reportSegPostAdopDga;
    }
    
    public void setReportSegPostAdopDga(Short reportSegPostAdopDga) {
        this.reportSegPostAdopDga = reportSegPostAdopDga;
    }
    public String getReportSegPostAdopDgaObs() {
        return this.reportSegPostAdopDgaObs;
    }
    
    public void setReportSegPostAdopDgaObs(String reportSegPostAdopDgaObs) {
        this.reportSegPostAdopDgaObs = reportSegPostAdopDgaObs;
    }
    public Short getFotografiaAdopHogar() {
        return this.fotografiaAdopHogar;
    }
    
    public void setFotografiaAdopHogar(Short fotografiaAdopHogar) {
        this.fotografiaAdopHogar = fotografiaAdopHogar;
    }
    public String getFotografiaAdopHogarObs() {
        return this.fotografiaAdopHogarObs;
    }
    
    public void setFotografiaAdopHogarObs(String fotografiaAdopHogarObs) {
        this.fotografiaAdopHogarObs = fotografiaAdopHogarObs;
    }
    public Short getCompromisoPostAdop() {
        return this.compromisoPostAdop;
    }
    
    public void setCompromisoPostAdop(Short compromisoPostAdop) {
        this.compromisoPostAdop = compromisoPostAdop;
    }
    public String getCompromisoPostAdopObs() {
        return this.compromisoPostAdopObs;
    }
    
    public void setCompromisoPostAdopObs(String compromisoPostAdopObs) {
        this.compromisoPostAdopObs = compromisoPostAdopObs;
    }




}


