package com.mimp.bean;
// Generated Nov 22, 2013 4:14:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpedienteFamilia generated by hbm2java
 */
public class ExpedienteFamilia  implements java.io.Serializable {


     private Integer idexpedienteFamilia;
     private Unidad unidad;
     private Familia familia;
     private Integer numero;
     private String expediente;
     private String ht;
     private String numeroExpediente;
     private Date fechaIngresoDga;
     private String estado;
     private Date tupa;
     private String nacionalidad;
     private Boolean rnsa;
     private Boolean rnaa;
     private String tipoFamilia;
     private String tipoListaEspera;
     private Set<Resolucion> resolucions = new HashSet<Resolucion>(0);
     private Set<Designacion> designacions = new HashSet<Designacion>(0);
     private Set<EstudioCaso> estudioCasos = new HashSet<EstudioCaso>(0);
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);

    public ExpedienteFamilia() {
    }

	
    public ExpedienteFamilia(Unidad unidad, Familia familia) {
        this.unidad = unidad;
        this.familia = familia;
    }
    public ExpedienteFamilia(Unidad unidad, Familia familia, Integer numero, String expediente, String ht, String numeroExpediente, Date fechaIngresoDga, String estado, Date tupa, String nacionalidad, Boolean rnsa, Boolean rnaa, String tipoFamilia, String tipoListaEspera, Set<Resolucion> resolucions, Set<Designacion> designacions, Set<EstudioCaso> estudioCasos, Set<Evaluacion> evaluacions) {
       this.unidad = unidad;
       this.familia = familia;
       this.numero = numero;
       this.expediente = expediente;
       this.ht = ht;
       this.numeroExpediente = numeroExpediente;
       this.fechaIngresoDga = fechaIngresoDga;
       this.estado = estado;
       this.tupa = tupa;
       this.nacionalidad = nacionalidad;
       this.rnsa = rnsa;
       this.rnaa = rnaa;
       this.tipoFamilia = tipoFamilia;
       this.tipoListaEspera = tipoListaEspera;
       this.resolucions = resolucions;
       this.designacions = designacions;
       this.estudioCasos = estudioCasos;
       this.evaluacions = evaluacions;
    }
   
    public Integer getIdexpedienteFamilia() {
        return this.idexpedienteFamilia;
    }
    
    public void setIdexpedienteFamilia(Integer idexpedienteFamilia) {
        this.idexpedienteFamilia = idexpedienteFamilia;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }
    public String getHt() {
        return this.ht;
    }
    
    public void setHt(String ht) {
        this.ht = ht;
    }
    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }
    
    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }
    public Date getFechaIngresoDga() {
        return this.fechaIngresoDga;
    }
    
    public void setFechaIngresoDga(Date fechaIngresoDga) {
        this.fechaIngresoDga = fechaIngresoDga;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getTupa() {
        return this.tupa;
    }
    
    public void setTupa(Date tupa) {
        this.tupa = tupa;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Boolean getRnsa() {
        return this.rnsa;
    }
    
    public void setRnsa(Boolean rnsa) {
        this.rnsa = rnsa;
    }
    public Boolean getRnaa() {
        return this.rnaa;
    }
    
    public void setRnaa(Boolean rnaa) {
        this.rnaa = rnaa;
    }
    public String getTipoFamilia() {
        return this.tipoFamilia;
    }
    
    public void setTipoFamilia(String tipoFamilia) {
        this.tipoFamilia = tipoFamilia;
    }
    public String getTipoListaEspera() {
        return this.tipoListaEspera;
    }
    
    public void setTipoListaEspera(String tipoListaEspera) {
        this.tipoListaEspera = tipoListaEspera;
    }
    public Set<Resolucion> getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set<Resolucion> resolucions) {
        this.resolucions = resolucions;
    }
    public Set<Designacion> getDesignacions() {
        return this.designacions;
    }
    
    public void setDesignacions(Set<Designacion> designacions) {
        this.designacions = designacions;
    }
    public Set<EstudioCaso> getEstudioCasos() {
        return this.estudioCasos;
    }
    
    public void setEstudioCasos(Set<EstudioCaso> estudioCasos) {
        this.estudioCasos = estudioCasos;
    }
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }




}


