package com.mimp.bean;
// Generated Dec 13, 2013 9:53:43 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia  implements java.io.Serializable {


     private long idfamilia;
     private Entidad entidad;
     private String user;
     private String pass;
     private String correo;
     private Short habilitado;
     private String constancia;
     private Set<ExpedienteFamilia> expedienteFamilias = new HashSet<ExpedienteFamilia>(0);
     private Set<AsistenciaFR> asistenciaFRs = new HashSet<AsistenciaFR>(0);
     private Set<Atencion> atencions = new HashSet<Atencion>(0);
     private Set<FormularioSesion> formularioSesions = new HashSet<FormularioSesion>(0);
     private Set<FichaSolicitudAdopcion> fichaSolicitudAdopcions = new HashSet<FichaSolicitudAdopcion>(0);
     private Set<InfoFamilia> infoFamilias = new HashSet<InfoFamilia>(0);
     private Set<PostAdopcion> postAdopcions = new HashSet<PostAdopcion>(0);

    public Familia() {
    }

	
    public Familia(long idfamilia) {
        this.idfamilia = idfamilia;
    }
    public Familia(long idfamilia, Entidad entidad, String user, String pass, String correo, Short habilitado, String constancia, Set<ExpedienteFamilia> expedienteFamilias, Set<AsistenciaFR> asistenciaFRs, Set<Atencion> atencions, Set<FormularioSesion> formularioSesions, Set<FichaSolicitudAdopcion> fichaSolicitudAdopcions, Set<InfoFamilia> infoFamilias, Set<PostAdopcion> postAdopcions) {
       this.idfamilia = idfamilia;
       this.entidad = entidad;
       this.user = user;
       this.pass = pass;
       this.correo = correo;
       this.habilitado = habilitado;
       this.constancia = constancia;
       this.expedienteFamilias = expedienteFamilias;
       this.asistenciaFRs = asistenciaFRs;
       this.atencions = atencions;
       this.formularioSesions = formularioSesions;
       this.fichaSolicitudAdopcions = fichaSolicitudAdopcions;
       this.infoFamilias = infoFamilias;
       this.postAdopcions = postAdopcions;
    }
   
    public long getIdfamilia() {
        return this.idfamilia;
    }
    
    public void setIdfamilia(long idfamilia) {
        this.idfamilia = idfamilia;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Short getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Short habilitado) {
        this.habilitado = habilitado;
    }
    public String getConstancia() {
        return this.constancia;
    }
    
    public void setConstancia(String constancia) {
        this.constancia = constancia;
    }
    public Set<ExpedienteFamilia> getExpedienteFamilias() {
        return this.expedienteFamilias;
    }
    
    public void setExpedienteFamilias(Set<ExpedienteFamilia> expedienteFamilias) {
        this.expedienteFamilias = expedienteFamilias;
    }
    public Set<AsistenciaFR> getAsistenciaFRs() {
        return this.asistenciaFRs;
    }
    
    public void setAsistenciaFRs(Set<AsistenciaFR> asistenciaFRs) {
        this.asistenciaFRs = asistenciaFRs;
    }
    public Set<Atencion> getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set<Atencion> atencions) {
        this.atencions = atencions;
    }
    public Set<FormularioSesion> getFormularioSesions() {
        return this.formularioSesions;
    }
    
    public void setFormularioSesions(Set<FormularioSesion> formularioSesions) {
        this.formularioSesions = formularioSesions;
    }
    public Set<FichaSolicitudAdopcion> getFichaSolicitudAdopcions() {
        return this.fichaSolicitudAdopcions;
    }
    
    public void setFichaSolicitudAdopcions(Set<FichaSolicitudAdopcion> fichaSolicitudAdopcions) {
        this.fichaSolicitudAdopcions = fichaSolicitudAdopcions;
    }
    public Set<InfoFamilia> getInfoFamilias() {
        return this.infoFamilias;
    }
    
    public void setInfoFamilias(Set<InfoFamilia> infoFamilias) {
        this.infoFamilias = infoFamilias;
    }
    public Set<PostAdopcion> getPostAdopcions() {
        return this.postAdopcions;
    }
    
    public void setPostAdopcions(Set<PostAdopcion> postAdopcions) {
        this.postAdopcions = postAdopcions;
    }




}


