package com.mimp.bean;
// Generated Dec 4, 2013 5:48:18 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FichaSolicitudAdopcion generated by hbm2java
 */
public class FichaSolicitudAdopcion  implements java.io.Serializable {


     private Integer idfichaSolicitudAdopcion;
     private Familia familia;
     private String numeroFicha;
     private String hojaRuta;
     private String estadoCivil;
     private Date fechaIngreso;
     private String fijo;
     private String domicilio;
     private String depRes;
     private String propiedadVivienda;
     private String tipoVivienda;
     private Integer areaVivTotal;
     private Integer areaVivConst;
     private String distVivenda;
     private Boolean luz;
     private Boolean agua;
     private Boolean desague;
     private String otrosServ;
     private String materConst;
     private String pared;
     private String techo;
     private String piso;
     private Byte NProcAdopPrev;
     private String anhoProceso;
     private Boolean procesoPrep;
     private Boolean procesoEval;
     private String motivoAdopcion;
     private Boolean nnaIncesto;
     private Boolean nnaMental;
     private Boolean nnaEpilepsia;
     private Boolean nnaAbuso;
     private Boolean nnaSifilis;
     private Boolean nnaSeguiMedico;
     private Boolean nnaOperacion;
     private Boolean nnaHiperactivo;
     private Boolean nnaEspecial;
     private Boolean nnaEnfermo;
     private Boolean nnaMayor;
     private Boolean nnaAdolescente;
     private Boolean nnaHermano;
     private Boolean nnaForaneo;
     private String rptaForaneo;
     private Set<Solicitante> solicitantes = new HashSet<Solicitante>(0);
     private Set<Hijo> hijos = new HashSet<Hijo>(0);
     private Set<Residente> residentes = new HashSet<Residente>(0);

    public FichaSolicitudAdopcion() {
    }

	
    public FichaSolicitudAdopcion(Familia familia) {
        this.familia = familia;
    }
    public FichaSolicitudAdopcion(Familia familia, String numeroFicha, String hojaRuta, String estadoCivil, Date fechaIngreso, String fijo, String domicilio, String depRes, String propiedadVivienda, String tipoVivienda, Integer areaVivTotal, Integer areaVivConst, String distVivenda, Boolean luz, Boolean agua, Boolean desague, String otrosServ, String materConst, String pared, String techo, String piso, Byte NProcAdopPrev, String anhoProceso, Boolean procesoPrep, Boolean procesoEval, String motivoAdopcion, Boolean nnaIncesto, Boolean nnaMental, Boolean nnaEpilepsia, Boolean nnaAbuso, Boolean nnaSifilis, Boolean nnaSeguiMedico, Boolean nnaOperacion, Boolean nnaHiperactivo, Boolean nnaEspecial, Boolean nnaEnfermo, Boolean nnaMayor, Boolean nnaAdolescente, Boolean nnaHermano, Boolean nnaForaneo, String rptaForaneo, Set<Solicitante> solicitantes, Set<Hijo> hijos, Set<Residente> residentes) {
       this.familia = familia;
       this.numeroFicha = numeroFicha;
       this.hojaRuta = hojaRuta;
       this.estadoCivil = estadoCivil;
       this.fechaIngreso = fechaIngreso;
       this.fijo = fijo;
       this.domicilio = domicilio;
       this.depRes = depRes;
       this.propiedadVivienda = propiedadVivienda;
       this.tipoVivienda = tipoVivienda;
       this.areaVivTotal = areaVivTotal;
       this.areaVivConst = areaVivConst;
       this.distVivenda = distVivenda;
       this.luz = luz;
       this.agua = agua;
       this.desague = desague;
       this.otrosServ = otrosServ;
       this.materConst = materConst;
       this.pared = pared;
       this.techo = techo;
       this.piso = piso;
       this.NProcAdopPrev = NProcAdopPrev;
       this.anhoProceso = anhoProceso;
       this.procesoPrep = procesoPrep;
       this.procesoEval = procesoEval;
       this.motivoAdopcion = motivoAdopcion;
       this.nnaIncesto = nnaIncesto;
       this.nnaMental = nnaMental;
       this.nnaEpilepsia = nnaEpilepsia;
       this.nnaAbuso = nnaAbuso;
       this.nnaSifilis = nnaSifilis;
       this.nnaSeguiMedico = nnaSeguiMedico;
       this.nnaOperacion = nnaOperacion;
       this.nnaHiperactivo = nnaHiperactivo;
       this.nnaEspecial = nnaEspecial;
       this.nnaEnfermo = nnaEnfermo;
       this.nnaMayor = nnaMayor;
       this.nnaAdolescente = nnaAdolescente;
       this.nnaHermano = nnaHermano;
       this.nnaForaneo = nnaForaneo;
       this.rptaForaneo = rptaForaneo;
       this.solicitantes = solicitantes;
       this.hijos = hijos;
       this.residentes = residentes;
    }
   
    public Integer getIdfichaSolicitudAdopcion() {
        return this.idfichaSolicitudAdopcion;
    }
    
    public void setIdfichaSolicitudAdopcion(Integer idfichaSolicitudAdopcion) {
        this.idfichaSolicitudAdopcion = idfichaSolicitudAdopcion;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getNumeroFicha() {
        return this.numeroFicha;
    }
    
    public void setNumeroFicha(String numeroFicha) {
        this.numeroFicha = numeroFicha;
    }
    public String getHojaRuta() {
        return this.hojaRuta;
    }
    
    public void setHojaRuta(String hojaRuta) {
        this.hojaRuta = hojaRuta;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getFijo() {
        return this.fijo;
    }
    
    public void setFijo(String fijo) {
        this.fijo = fijo;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getDepRes() {
        return this.depRes;
    }
    
    public void setDepRes(String depRes) {
        this.depRes = depRes;
    }
    public String getPropiedadVivienda() {
        return this.propiedadVivienda;
    }
    
    public void setPropiedadVivienda(String propiedadVivienda) {
        this.propiedadVivienda = propiedadVivienda;
    }
    public String getTipoVivienda() {
        return this.tipoVivienda;
    }
    
    public void setTipoVivienda(String tipoVivienda) {
        this.tipoVivienda = tipoVivienda;
    }
    public Integer getAreaVivTotal() {
        return this.areaVivTotal;
    }
    
    public void setAreaVivTotal(Integer areaVivTotal) {
        this.areaVivTotal = areaVivTotal;
    }
    public Integer getAreaVivConst() {
        return this.areaVivConst;
    }
    
    public void setAreaVivConst(Integer areaVivConst) {
        this.areaVivConst = areaVivConst;
    }
    public String getDistVivenda() {
        return this.distVivenda;
    }
    
    public void setDistVivenda(String distVivenda) {
        this.distVivenda = distVivenda;
    }
    public Boolean getLuz() {
        return this.luz;
    }
    
    public void setLuz(Boolean luz) {
        this.luz = luz;
    }
    public Boolean getAgua() {
        return this.agua;
    }
    
    public void setAgua(Boolean agua) {
        this.agua = agua;
    }
    public Boolean getDesague() {
        return this.desague;
    }
    
    public void setDesague(Boolean desague) {
        this.desague = desague;
    }
    public String getOtrosServ() {
        return this.otrosServ;
    }
    
    public void setOtrosServ(String otrosServ) {
        this.otrosServ = otrosServ;
    }
    public String getMaterConst() {
        return this.materConst;
    }
    
    public void setMaterConst(String materConst) {
        this.materConst = materConst;
    }
    public String getPared() {
        return this.pared;
    }
    
    public void setPared(String pared) {
        this.pared = pared;
    }
    public String getTecho() {
        return this.techo;
    }
    
    public void setTecho(String techo) {
        this.techo = techo;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Byte getNProcAdopPrev() {
        return this.NProcAdopPrev;
    }
    
    public void setNProcAdopPrev(Byte NProcAdopPrev) {
        this.NProcAdopPrev = NProcAdopPrev;
    }
    public String getAnhoProceso() {
        return this.anhoProceso;
    }
    
    public void setAnhoProceso(String anhoProceso) {
        this.anhoProceso = anhoProceso;
    }
    public Boolean getProcesoPrep() {
        return this.procesoPrep;
    }
    
    public void setProcesoPrep(Boolean procesoPrep) {
        this.procesoPrep = procesoPrep;
    }
    public Boolean getProcesoEval() {
        return this.procesoEval;
    }
    
    public void setProcesoEval(Boolean procesoEval) {
        this.procesoEval = procesoEval;
    }
    public String getMotivoAdopcion() {
        return this.motivoAdopcion;
    }
    
    public void setMotivoAdopcion(String motivoAdopcion) {
        this.motivoAdopcion = motivoAdopcion;
    }
    public Boolean getNnaIncesto() {
        return this.nnaIncesto;
    }
    
    public void setNnaIncesto(Boolean nnaIncesto) {
        this.nnaIncesto = nnaIncesto;
    }
    public Boolean getNnaMental() {
        return this.nnaMental;
    }
    
    public void setNnaMental(Boolean nnaMental) {
        this.nnaMental = nnaMental;
    }
    public Boolean getNnaEpilepsia() {
        return this.nnaEpilepsia;
    }
    
    public void setNnaEpilepsia(Boolean nnaEpilepsia) {
        this.nnaEpilepsia = nnaEpilepsia;
    }
    public Boolean getNnaAbuso() {
        return this.nnaAbuso;
    }
    
    public void setNnaAbuso(Boolean nnaAbuso) {
        this.nnaAbuso = nnaAbuso;
    }
    public Boolean getNnaSifilis() {
        return this.nnaSifilis;
    }
    
    public void setNnaSifilis(Boolean nnaSifilis) {
        this.nnaSifilis = nnaSifilis;
    }
    public Boolean getNnaSeguiMedico() {
        return this.nnaSeguiMedico;
    }
    
    public void setNnaSeguiMedico(Boolean nnaSeguiMedico) {
        this.nnaSeguiMedico = nnaSeguiMedico;
    }
    public Boolean getNnaOperacion() {
        return this.nnaOperacion;
    }
    
    public void setNnaOperacion(Boolean nnaOperacion) {
        this.nnaOperacion = nnaOperacion;
    }
    public Boolean getNnaHiperactivo() {
        return this.nnaHiperactivo;
    }
    
    public void setNnaHiperactivo(Boolean nnaHiperactivo) {
        this.nnaHiperactivo = nnaHiperactivo;
    }
    public Boolean getNnaEspecial() {
        return this.nnaEspecial;
    }
    
    public void setNnaEspecial(Boolean nnaEspecial) {
        this.nnaEspecial = nnaEspecial;
    }
    public Boolean getNnaEnfermo() {
        return this.nnaEnfermo;
    }
    
    public void setNnaEnfermo(Boolean nnaEnfermo) {
        this.nnaEnfermo = nnaEnfermo;
    }
    public Boolean getNnaMayor() {
        return this.nnaMayor;
    }
    
    public void setNnaMayor(Boolean nnaMayor) {
        this.nnaMayor = nnaMayor;
    }
    public Boolean getNnaAdolescente() {
        return this.nnaAdolescente;
    }
    
    public void setNnaAdolescente(Boolean nnaAdolescente) {
        this.nnaAdolescente = nnaAdolescente;
    }
    public Boolean getNnaHermano() {
        return this.nnaHermano;
    }
    
    public void setNnaHermano(Boolean nnaHermano) {
        this.nnaHermano = nnaHermano;
    }
    public Boolean getNnaForaneo() {
        return this.nnaForaneo;
    }
    
    public void setNnaForaneo(Boolean nnaForaneo) {
        this.nnaForaneo = nnaForaneo;
    }
    public String getRptaForaneo() {
        return this.rptaForaneo;
    }
    
    public void setRptaForaneo(String rptaForaneo) {
        this.rptaForaneo = rptaForaneo;
    }
    public Set<Solicitante> getSolicitantes() {
        return this.solicitantes;
    }
    
    public void setSolicitantes(Set<Solicitante> solicitantes) {
        this.solicitantes = solicitantes;
    }
    public Set<Hijo> getHijos() {
        return this.hijos;
    }
    
    public void setHijos(Set<Hijo> hijos) {
        this.hijos = hijos;
    }
    public Set<Residente> getResidentes() {
        return this.residentes;
    }
    
    public void setResidentes(Set<Residente> residentes) {
        this.residentes = residentes;
    }




}


