package com.mimp.bean;
// Generated Dec 23, 2013 10:39:27 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FichaSolicitudAdopcion generated by hbm2java
 */
public class FichaSolicitudAdopcion  implements java.io.Serializable {


     private long idfichaSolicitudAdopcion;
     private Familia familia;
     private String numeroFicha;
     private String hojaRuta;
     private String estadoCivil;
     private Date fechaIngreso;
     private String fijo;
     private String domicilio;
     private String depRes;
     private String propiedadVivienda;
     private String tipoVivienda;
     private Long areaVivTotal;
     private Long areaVivConst;
     private String distVivenda;
     private Short luz;
     private Short agua;
     private Short desague;
     private String otrosServ;
     private String materConst;
     private String pared;
     private String techo;
     private String piso;
     private Short NProcAdopPrev;
     private String anhoProceso;
     private Short procesoPrep;
     private Short procesoEval;
     private String motivoAdopcion;
     private Short nnaIncesto;
     private Short nnaMental;
     private Short nnaEpilepsia;
     private Short nnaAbuso;
     private Short nnaSifilis;
     private Short nnaSeguiMedico;
     private Short nnaOperacion;
     private Short nnaHiperactivo;
     private Short nnaEspecial;
     private Short nnaEnfermo;
     private Short nnaMayor;
     private Short nnaAdolescente;
     private Short nnaHermano;
     private Short nnaForaneo;
     private String rptaForaneo;
     private Date fechaMatrimonio;
     private Set<Solicitante> solicitantes = new HashSet<Solicitante>(0);
     private Set<Residente> residentes = new HashSet<Residente>(0);
     private Set<Hijo> hijos = new HashSet<Hijo>(0);

    public FichaSolicitudAdopcion() {
    }

	
    public FichaSolicitudAdopcion(long idfichaSolicitudAdopcion, Familia familia) {
        this.idfichaSolicitudAdopcion = idfichaSolicitudAdopcion;
        this.familia = familia;
    }
    public FichaSolicitudAdopcion(long idfichaSolicitudAdopcion, Familia familia, String numeroFicha, String hojaRuta, String estadoCivil, Date fechaIngreso, String fijo, String domicilio, String depRes, String propiedadVivienda, String tipoVivienda, Long areaVivTotal, Long areaVivConst, String distVivenda, Short luz, Short agua, Short desague, String otrosServ, String materConst, String pared, String techo, String piso, Short NProcAdopPrev, String anhoProceso, Short procesoPrep, Short procesoEval, String motivoAdopcion, Short nnaIncesto, Short nnaMental, Short nnaEpilepsia, Short nnaAbuso, Short nnaSifilis, Short nnaSeguiMedico, Short nnaOperacion, Short nnaHiperactivo, Short nnaEspecial, Short nnaEnfermo, Short nnaMayor, Short nnaAdolescente, Short nnaHermano, Short nnaForaneo, String rptaForaneo, Date fechaMatrimonio, Set<Solicitante> solicitantes, Set<Residente> residentes, Set<Hijo> hijos) {
       this.idfichaSolicitudAdopcion = idfichaSolicitudAdopcion;
       this.familia = familia;
       this.numeroFicha = numeroFicha;
       this.hojaRuta = hojaRuta;
       this.estadoCivil = estadoCivil;
       this.fechaIngreso = fechaIngreso;
       this.fijo = fijo;
       this.domicilio = domicilio;
       this.depRes = depRes;
       this.propiedadVivienda = propiedadVivienda;
       this.tipoVivienda = tipoVivienda;
       this.areaVivTotal = areaVivTotal;
       this.areaVivConst = areaVivConst;
       this.distVivenda = distVivenda;
       this.luz = luz;
       this.agua = agua;
       this.desague = desague;
       this.otrosServ = otrosServ;
       this.materConst = materConst;
       this.pared = pared;
       this.techo = techo;
       this.piso = piso;
       this.NProcAdopPrev = NProcAdopPrev;
       this.anhoProceso = anhoProceso;
       this.procesoPrep = procesoPrep;
       this.procesoEval = procesoEval;
       this.motivoAdopcion = motivoAdopcion;
       this.nnaIncesto = nnaIncesto;
       this.nnaMental = nnaMental;
       this.nnaEpilepsia = nnaEpilepsia;
       this.nnaAbuso = nnaAbuso;
       this.nnaSifilis = nnaSifilis;
       this.nnaSeguiMedico = nnaSeguiMedico;
       this.nnaOperacion = nnaOperacion;
       this.nnaHiperactivo = nnaHiperactivo;
       this.nnaEspecial = nnaEspecial;
       this.nnaEnfermo = nnaEnfermo;
       this.nnaMayor = nnaMayor;
       this.nnaAdolescente = nnaAdolescente;
       this.nnaHermano = nnaHermano;
       this.nnaForaneo = nnaForaneo;
       this.rptaForaneo = rptaForaneo;
       this.fechaMatrimonio = fechaMatrimonio;
       this.solicitantes = solicitantes;
       this.residentes = residentes;
       this.hijos = hijos;
    }
   
    public long getIdfichaSolicitudAdopcion() {
        return this.idfichaSolicitudAdopcion;
    }
    
    public void setIdfichaSolicitudAdopcion(long idfichaSolicitudAdopcion) {
        this.idfichaSolicitudAdopcion = idfichaSolicitudAdopcion;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getNumeroFicha() {
        return this.numeroFicha;
    }
    
    public void setNumeroFicha(String numeroFicha) {
        this.numeroFicha = numeroFicha;
    }
    public String getHojaRuta() {
        return this.hojaRuta;
    }
    
    public void setHojaRuta(String hojaRuta) {
        this.hojaRuta = hojaRuta;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getFijo() {
        return this.fijo;
    }
    
    public void setFijo(String fijo) {
        this.fijo = fijo;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getDepRes() {
        return this.depRes;
    }
    
    public void setDepRes(String depRes) {
        this.depRes = depRes;
    }
    public String getPropiedadVivienda() {
        return this.propiedadVivienda;
    }
    
    public void setPropiedadVivienda(String propiedadVivienda) {
        this.propiedadVivienda = propiedadVivienda;
    }
    public String getTipoVivienda() {
        return this.tipoVivienda;
    }
    
    public void setTipoVivienda(String tipoVivienda) {
        this.tipoVivienda = tipoVivienda;
    }
    public Long getAreaVivTotal() {
        return this.areaVivTotal;
    }
    
    public void setAreaVivTotal(Long areaVivTotal) {
        this.areaVivTotal = areaVivTotal;
    }
    public Long getAreaVivConst() {
        return this.areaVivConst;
    }
    
    public void setAreaVivConst(Long areaVivConst) {
        this.areaVivConst = areaVivConst;
    }
    public String getDistVivenda() {
        return this.distVivenda;
    }
    
    public void setDistVivenda(String distVivenda) {
        this.distVivenda = distVivenda;
    }
    public Short getLuz() {
        return this.luz;
    }
    
    public void setLuz(Short luz) {
        this.luz = luz;
    }
    public Short getAgua() {
        return this.agua;
    }
    
    public void setAgua(Short agua) {
        this.agua = agua;
    }
    public Short getDesague() {
        return this.desague;
    }
    
    public void setDesague(Short desague) {
        this.desague = desague;
    }
    public String getOtrosServ() {
        return this.otrosServ;
    }
    
    public void setOtrosServ(String otrosServ) {
        this.otrosServ = otrosServ;
    }
    public String getMaterConst() {
        return this.materConst;
    }
    
    public void setMaterConst(String materConst) {
        this.materConst = materConst;
    }
    public String getPared() {
        return this.pared;
    }
    
    public void setPared(String pared) {
        this.pared = pared;
    }
    public String getTecho() {
        return this.techo;
    }
    
    public void setTecho(String techo) {
        this.techo = techo;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Short getNProcAdopPrev() {
        return this.NProcAdopPrev;
    }
    
    public void setNProcAdopPrev(Short NProcAdopPrev) {
        this.NProcAdopPrev = NProcAdopPrev;
    }
    public String getAnhoProceso() {
        return this.anhoProceso;
    }
    
    public void setAnhoProceso(String anhoProceso) {
        this.anhoProceso = anhoProceso;
    }
    public Short getProcesoPrep() {
        return this.procesoPrep;
    }
    
    public void setProcesoPrep(Short procesoPrep) {
        this.procesoPrep = procesoPrep;
    }
    public Short getProcesoEval() {
        return this.procesoEval;
    }
    
    public void setProcesoEval(Short procesoEval) {
        this.procesoEval = procesoEval;
    }
    public String getMotivoAdopcion() {
        return this.motivoAdopcion;
    }
    
    public void setMotivoAdopcion(String motivoAdopcion) {
        this.motivoAdopcion = motivoAdopcion;
    }
    public Short getNnaIncesto() {
        return this.nnaIncesto;
    }
    
    public void setNnaIncesto(Short nnaIncesto) {
        this.nnaIncesto = nnaIncesto;
    }
    public Short getNnaMental() {
        return this.nnaMental;
    }
    
    public void setNnaMental(Short nnaMental) {
        this.nnaMental = nnaMental;
    }
    public Short getNnaEpilepsia() {
        return this.nnaEpilepsia;
    }
    
    public void setNnaEpilepsia(Short nnaEpilepsia) {
        this.nnaEpilepsia = nnaEpilepsia;
    }
    public Short getNnaAbuso() {
        return this.nnaAbuso;
    }
    
    public void setNnaAbuso(Short nnaAbuso) {
        this.nnaAbuso = nnaAbuso;
    }
    public Short getNnaSifilis() {
        return this.nnaSifilis;
    }
    
    public void setNnaSifilis(Short nnaSifilis) {
        this.nnaSifilis = nnaSifilis;
    }
    public Short getNnaSeguiMedico() {
        return this.nnaSeguiMedico;
    }
    
    public void setNnaSeguiMedico(Short nnaSeguiMedico) {
        this.nnaSeguiMedico = nnaSeguiMedico;
    }
    public Short getNnaOperacion() {
        return this.nnaOperacion;
    }
    
    public void setNnaOperacion(Short nnaOperacion) {
        this.nnaOperacion = nnaOperacion;
    }
    public Short getNnaHiperactivo() {
        return this.nnaHiperactivo;
    }
    
    public void setNnaHiperactivo(Short nnaHiperactivo) {
        this.nnaHiperactivo = nnaHiperactivo;
    }
    public Short getNnaEspecial() {
        return this.nnaEspecial;
    }
    
    public void setNnaEspecial(Short nnaEspecial) {
        this.nnaEspecial = nnaEspecial;
    }
    public Short getNnaEnfermo() {
        return this.nnaEnfermo;
    }
    
    public void setNnaEnfermo(Short nnaEnfermo) {
        this.nnaEnfermo = nnaEnfermo;
    }
    public Short getNnaMayor() {
        return this.nnaMayor;
    }
    
    public void setNnaMayor(Short nnaMayor) {
        this.nnaMayor = nnaMayor;
    }
    public Short getNnaAdolescente() {
        return this.nnaAdolescente;
    }
    
    public void setNnaAdolescente(Short nnaAdolescente) {
        this.nnaAdolescente = nnaAdolescente;
    }
    public Short getNnaHermano() {
        return this.nnaHermano;
    }
    
    public void setNnaHermano(Short nnaHermano) {
        this.nnaHermano = nnaHermano;
    }
    public Short getNnaForaneo() {
        return this.nnaForaneo;
    }
    
    public void setNnaForaneo(Short nnaForaneo) {
        this.nnaForaneo = nnaForaneo;
    }
    public String getRptaForaneo() {
        return this.rptaForaneo;
    }
    
    public void setRptaForaneo(String rptaForaneo) {
        this.rptaForaneo = rptaForaneo;
    }
    public Date getFechaMatrimonio() {
        return this.fechaMatrimonio;
    }
    
    public void setFechaMatrimonio(Date fechaMatrimonio) {
        this.fechaMatrimonio = fechaMatrimonio;
    }
    public Set<Solicitante> getSolicitantes() {
        return this.solicitantes;
    }
    
    public void setSolicitantes(Set<Solicitante> solicitantes) {
        this.solicitantes = solicitantes;
    }
    public Set<Residente> getResidentes() {
        return this.residentes;
    }
    
    public void setResidentes(Set<Residente> residentes) {
        this.residentes = residentes;
    }
    public Set<Hijo> getHijos() {
        return this.hijos;
    }
    
    public void setHijos(Set<Hijo> hijos) {
        this.hijos = hijos;
    }




}


