package com.mimp.bean;
// Generated Dec 23, 2013 10:39:27 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private long idgrupo;
     private Taller taller;
     private String nombre;
     private Set<Turno2> turno2s = new HashSet<Turno2>(0);

    public Grupo() {
    }

	
    public Grupo(long idgrupo, Taller taller) {
        this.idgrupo = idgrupo;
        this.taller = taller;
    }
    public Grupo(long idgrupo, Taller taller, String nombre, Set<Turno2> turno2s) {
       this.idgrupo = idgrupo;
       this.taller = taller;
       this.nombre = nombre;
       this.turno2s = turno2s;
    }
   
    public long getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(long idgrupo) {
        this.idgrupo = idgrupo;
    }
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Turno2> getTurno2s() {
        return this.turno2s;
    }
    
    public void setTurno2s(Set<Turno2> turno2s) {
        this.turno2s = turno2s;
    }




}


