package com.mimp.bean;
// Generated 10/12/2013 03:07:34 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Hijo generated by hbm2java
 */
public class Hijo  implements java.io.Serializable {


     private Integer idhijo;
     private FichaSolicitudAdopcion fichaSolicitudAdopcion;
     private Date fechaNac;
     private Boolean biologico;
     private Date fechaAdop;
     private Byte edad;
     private String nombre;
     private String apellidoP;
     private String apellidoM;
     private String ocupacion;
     private String estadoSalud;
     private Boolean reside;

    public Hijo() {
    }

	
    public Hijo(FichaSolicitudAdopcion fichaSolicitudAdopcion) {
        this.fichaSolicitudAdopcion = fichaSolicitudAdopcion;
    }
    public Hijo(FichaSolicitudAdopcion fichaSolicitudAdopcion, Date fechaNac, Boolean biologico, Date fechaAdop, Byte edad, String nombre, String apellidoP, String apellidoM, String ocupacion, String estadoSalud, Boolean reside) {
       this.fichaSolicitudAdopcion = fichaSolicitudAdopcion;
       this.fechaNac = fechaNac;
       this.biologico = biologico;
       this.fechaAdop = fechaAdop;
       this.edad = edad;
       this.nombre = nombre;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.ocupacion = ocupacion;
       this.estadoSalud = estadoSalud;
       this.reside = reside;
    }
   
    public Integer getIdhijo() {
        return this.idhijo;
    }
    
    public void setIdhijo(Integer idhijo) {
        this.idhijo = idhijo;
    }
    public FichaSolicitudAdopcion getFichaSolicitudAdopcion() {
        return this.fichaSolicitudAdopcion;
    }
    
    public void setFichaSolicitudAdopcion(FichaSolicitudAdopcion fichaSolicitudAdopcion) {
        this.fichaSolicitudAdopcion = fichaSolicitudAdopcion;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Boolean getBiologico() {
        return this.biologico;
    }
    
    public void setBiologico(Boolean biologico) {
        this.biologico = biologico;
    }
    public Date getFechaAdop() {
        return this.fechaAdop;
    }
    
    public void setFechaAdop(Date fechaAdop) {
        this.fechaAdop = fechaAdop;
    }
    public Byte getEdad() {
        return this.edad;
    }
    
    public void setEdad(Byte edad) {
        this.edad = edad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getEstadoSalud() {
        return this.estadoSalud;
    }
    
    public void setEstadoSalud(String estadoSalud) {
        this.estadoSalud = estadoSalud;
    }
    public Boolean getReside() {
        return this.reside;
    }
    
    public void setReside(Boolean reside) {
        this.reside = reside;
    }




}


