package com.mimp.bean;
// Generated Dec 23, 2013 3:56:21 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * HijoAct generated by hbm2java
 */
public class HijoAct  implements java.io.Serializable {


     private long idhijoAct;
     private InfoFamilia infoFamilia;
     private Date fechaNac;
     private Short biologico;
     private Date fechaAdop;
     private String nombre;
     private String apellidoP;
     private String apellidoM;
     private String ocupacion;
     private String estadoSalud;
     private Short reside;

    public HijoAct() {
    }

	
    public HijoAct(long idhijoAct, InfoFamilia infoFamilia) {
        this.idhijoAct = idhijoAct;
        this.infoFamilia = infoFamilia;
    }
    public HijoAct(long idhijoAct, InfoFamilia infoFamilia, Date fechaNac, Short biologico, Date fechaAdop, String nombre, String apellidoP, String apellidoM, String ocupacion, String estadoSalud, Short reside) {
       this.idhijoAct = idhijoAct;
       this.infoFamilia = infoFamilia;
       this.fechaNac = fechaNac;
       this.biologico = biologico;
       this.fechaAdop = fechaAdop;
       this.nombre = nombre;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.ocupacion = ocupacion;
       this.estadoSalud = estadoSalud;
       this.reside = reside;
    }
   
    public long getIdhijoAct() {
        return this.idhijoAct;
    }
    
    public void setIdhijoAct(long idhijoAct) {
        this.idhijoAct = idhijoAct;
    }
    public InfoFamilia getInfoFamilia() {
        return this.infoFamilia;
    }
    
    public void setInfoFamilia(InfoFamilia infoFamilia) {
        this.infoFamilia = infoFamilia;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Short getBiologico() {
        return this.biologico;
    }
    
    public void setBiologico(Short biologico) {
        this.biologico = biologico;
    }
    public Date getFechaAdop() {
        return this.fechaAdop;
    }
    
    public void setFechaAdop(Date fechaAdop) {
        this.fechaAdop = fechaAdop;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getEstadoSalud() {
        return this.estadoSalud;
    }
    
    public void setEstadoSalud(String estadoSalud) {
        this.estadoSalud = estadoSalud;
    }
    public Short getReside() {
        return this.reside;
    }
    
    public void setReside(Short reside) {
        this.reside = reside;
    }




}


