package com.mimp.bean;
// Generated 5/12/2013 05:37:51 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InfoFamilia generated by hbm2java
 */
public class InfoFamilia  implements java.io.Serializable {


     private Integer idinfoFamilia;
     private Familia familia;
     private String hojaReferencia;
     private String depRes;
     private String paisRes;
     private String domicilio;
     private String propiedadVivienda;
     private String tipoVivienda;
     private Integer areaVivTotal;
     private Integer areaVivConst;
     private String distVivienda;
     private Boolean luz;
     private Boolean agua;
     private Boolean desague;
     private String otrosServ;
     private String materConst;
     private String pared;
     private String techo;
     private String piso;
     private Character nivelSocioeconomico;
     private Byte expectativaEdad;
     private String expectativaGenero;
     private String origenHijos;
     private Boolean puedeViajar;
     private String predisposicionAp;
     private String condicion;
     private String antecedenteFamilia;
     private Date fechaAntecedenteFamilia;
     private String observaciones;
     private Boolean nnaIncesto;
     private Boolean nnaMental;
     private Boolean nnaEpilepsia;
     private Boolean nnaAbuso;
     private Boolean nnaSifilis;
     private Boolean nnaSeguiMedico;
     private Boolean nnaOperacion;
     private Boolean nnaHiperactivo;
     private Boolean nnaEspecial;
     private Boolean nnaEnfermo;
     private Boolean nnaMayor;
     private Boolean nnaAdolescente;
     private Boolean nnaHermano;
     private Set<Adoptante> adoptantes = new HashSet<Adoptante>(0);
     private Set<ResidenteAct> residenteActs = new HashSet<ResidenteAct>(0);
     private Set<HijoAct> hijoActs = new HashSet<HijoAct>(0);

    public InfoFamilia() {
    }

	
    public InfoFamilia(Familia familia) {
        this.familia = familia;
    }
    public InfoFamilia(Familia familia, String hojaReferencia, String depRes, String paisRes, String domicilio, String propiedadVivienda, String tipoVivienda, Integer areaVivTotal, Integer areaVivConst, String distVivienda, Boolean luz, Boolean agua, Boolean desague, String otrosServ, String materConst, String pared, String techo, String piso, Character nivelSocioeconomico, Byte expectativaEdad, String expectativaGenero, String origenHijos, Boolean puedeViajar, String predisposicionAp, String condicion, String antecedenteFamilia, Date fechaAntecedenteFamilia, String observaciones, Boolean nnaIncesto, Boolean nnaMental, Boolean nnaEpilepsia, Boolean nnaAbuso, Boolean nnaSifilis, Boolean nnaSeguiMedico, Boolean nnaOperacion, Boolean nnaHiperactivo, Boolean nnaEspecial, Boolean nnaEnfermo, Boolean nnaMayor, Boolean nnaAdolescente, Boolean nnaHermano, Set<Adoptante> adoptantes, Set<ResidenteAct> residenteActs, Set<HijoAct> hijoActs) {
       this.familia = familia;
       this.hojaReferencia = hojaReferencia;
       this.depRes = depRes;
       this.paisRes = paisRes;
       this.domicilio = domicilio;
       this.propiedadVivienda = propiedadVivienda;
       this.tipoVivienda = tipoVivienda;
       this.areaVivTotal = areaVivTotal;
       this.areaVivConst = areaVivConst;
       this.distVivienda = distVivienda;
       this.luz = luz;
       this.agua = agua;
       this.desague = desague;
       this.otrosServ = otrosServ;
       this.materConst = materConst;
       this.pared = pared;
       this.techo = techo;
       this.piso = piso;
       this.nivelSocioeconomico = nivelSocioeconomico;
       this.expectativaEdad = expectativaEdad;
       this.expectativaGenero = expectativaGenero;
       this.origenHijos = origenHijos;
       this.puedeViajar = puedeViajar;
       this.predisposicionAp = predisposicionAp;
       this.condicion = condicion;
       this.antecedenteFamilia = antecedenteFamilia;
       this.fechaAntecedenteFamilia = fechaAntecedenteFamilia;
       this.observaciones = observaciones;
       this.nnaIncesto = nnaIncesto;
       this.nnaMental = nnaMental;
       this.nnaEpilepsia = nnaEpilepsia;
       this.nnaAbuso = nnaAbuso;
       this.nnaSifilis = nnaSifilis;
       this.nnaSeguiMedico = nnaSeguiMedico;
       this.nnaOperacion = nnaOperacion;
       this.nnaHiperactivo = nnaHiperactivo;
       this.nnaEspecial = nnaEspecial;
       this.nnaEnfermo = nnaEnfermo;
       this.nnaMayor = nnaMayor;
       this.nnaAdolescente = nnaAdolescente;
       this.nnaHermano = nnaHermano;
       this.adoptantes = adoptantes;
       this.residenteActs = residenteActs;
       this.hijoActs = hijoActs;
    }
   
    public Integer getIdinfoFamilia() {
        return this.idinfoFamilia;
    }
    
    public void setIdinfoFamilia(Integer idinfoFamilia) {
        this.idinfoFamilia = idinfoFamilia;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getHojaReferencia() {
        return this.hojaReferencia;
    }
    
    public void setHojaReferencia(String hojaReferencia) {
        this.hojaReferencia = hojaReferencia;
    }
    public String getDepRes() {
        return this.depRes;
    }
    
    public void setDepRes(String depRes) {
        this.depRes = depRes;
    }
    public String getPaisRes() {
        return this.paisRes;
    }
    
    public void setPaisRes(String paisRes) {
        this.paisRes = paisRes;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getPropiedadVivienda() {
        return this.propiedadVivienda;
    }
    
    public void setPropiedadVivienda(String propiedadVivienda) {
        this.propiedadVivienda = propiedadVivienda;
    }
    public String getTipoVivienda() {
        return this.tipoVivienda;
    }
    
    public void setTipoVivienda(String tipoVivienda) {
        this.tipoVivienda = tipoVivienda;
    }
    public Integer getAreaVivTotal() {
        return this.areaVivTotal;
    }
    
    public void setAreaVivTotal(Integer areaVivTotal) {
        this.areaVivTotal = areaVivTotal;
    }
    public Integer getAreaVivConst() {
        return this.areaVivConst;
    }
    
    public void setAreaVivConst(Integer areaVivConst) {
        this.areaVivConst = areaVivConst;
    }
    public String getDistVivienda() {
        return this.distVivienda;
    }
    
    public void setDistVivienda(String distVivienda) {
        this.distVivienda = distVivienda;
    }
    public Boolean getLuz() {
        return this.luz;
    }
    
    public void setLuz(Boolean luz) {
        this.luz = luz;
    }
    public Boolean getAgua() {
        return this.agua;
    }
    
    public void setAgua(Boolean agua) {
        this.agua = agua;
    }
    public Boolean getDesague() {
        return this.desague;
    }
    
    public void setDesague(Boolean desague) {
        this.desague = desague;
    }
    public String getOtrosServ() {
        return this.otrosServ;
    }
    
    public void setOtrosServ(String otrosServ) {
        this.otrosServ = otrosServ;
    }
    public String getMaterConst() {
        return this.materConst;
    }
    
    public void setMaterConst(String materConst) {
        this.materConst = materConst;
    }
    public String getPared() {
        return this.pared;
    }
    
    public void setPared(String pared) {
        this.pared = pared;
    }
    public String getTecho() {
        return this.techo;
    }
    
    public void setTecho(String techo) {
        this.techo = techo;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Character getNivelSocioeconomico() {
        return this.nivelSocioeconomico;
    }
    
    public void setNivelSocioeconomico(Character nivelSocioeconomico) {
        this.nivelSocioeconomico = nivelSocioeconomico;
    }
    public Byte getExpectativaEdad() {
        return this.expectativaEdad;
    }
    
    public void setExpectativaEdad(Byte expectativaEdad) {
        this.expectativaEdad = expectativaEdad;
    }
    public String getExpectativaGenero() {
        return this.expectativaGenero;
    }
    
    public void setExpectativaGenero(String expectativaGenero) {
        this.expectativaGenero = expectativaGenero;
    }
    public String getOrigenHijos() {
        return this.origenHijos;
    }
    
    public void setOrigenHijos(String origenHijos) {
        this.origenHijos = origenHijos;
    }
    public Boolean getPuedeViajar() {
        return this.puedeViajar;
    }
    
    public void setPuedeViajar(Boolean puedeViajar) {
        this.puedeViajar = puedeViajar;
    }
    public String getPredisposicionAp() {
        return this.predisposicionAp;
    }
    
    public void setPredisposicionAp(String predisposicionAp) {
        this.predisposicionAp = predisposicionAp;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getAntecedenteFamilia() {
        return this.antecedenteFamilia;
    }
    
    public void setAntecedenteFamilia(String antecedenteFamilia) {
        this.antecedenteFamilia = antecedenteFamilia;
    }
    public Date getFechaAntecedenteFamilia() {
        return this.fechaAntecedenteFamilia;
    }
    
    public void setFechaAntecedenteFamilia(Date fechaAntecedenteFamilia) {
        this.fechaAntecedenteFamilia = fechaAntecedenteFamilia;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Boolean getNnaIncesto() {
        return this.nnaIncesto;
    }
    
    public void setNnaIncesto(Boolean nnaIncesto) {
        this.nnaIncesto = nnaIncesto;
    }
    public Boolean getNnaMental() {
        return this.nnaMental;
    }
    
    public void setNnaMental(Boolean nnaMental) {
        this.nnaMental = nnaMental;
    }
    public Boolean getNnaEpilepsia() {
        return this.nnaEpilepsia;
    }
    
    public void setNnaEpilepsia(Boolean nnaEpilepsia) {
        this.nnaEpilepsia = nnaEpilepsia;
    }
    public Boolean getNnaAbuso() {
        return this.nnaAbuso;
    }
    
    public void setNnaAbuso(Boolean nnaAbuso) {
        this.nnaAbuso = nnaAbuso;
    }
    public Boolean getNnaSifilis() {
        return this.nnaSifilis;
    }
    
    public void setNnaSifilis(Boolean nnaSifilis) {
        this.nnaSifilis = nnaSifilis;
    }
    public Boolean getNnaSeguiMedico() {
        return this.nnaSeguiMedico;
    }
    
    public void setNnaSeguiMedico(Boolean nnaSeguiMedico) {
        this.nnaSeguiMedico = nnaSeguiMedico;
    }
    public Boolean getNnaOperacion() {
        return this.nnaOperacion;
    }
    
    public void setNnaOperacion(Boolean nnaOperacion) {
        this.nnaOperacion = nnaOperacion;
    }
    public Boolean getNnaHiperactivo() {
        return this.nnaHiperactivo;
    }
    
    public void setNnaHiperactivo(Boolean nnaHiperactivo) {
        this.nnaHiperactivo = nnaHiperactivo;
    }
    public Boolean getNnaEspecial() {
        return this.nnaEspecial;
    }
    
    public void setNnaEspecial(Boolean nnaEspecial) {
        this.nnaEspecial = nnaEspecial;
    }
    public Boolean getNnaEnfermo() {
        return this.nnaEnfermo;
    }
    
    public void setNnaEnfermo(Boolean nnaEnfermo) {
        this.nnaEnfermo = nnaEnfermo;
    }
    public Boolean getNnaMayor() {
        return this.nnaMayor;
    }
    
    public void setNnaMayor(Boolean nnaMayor) {
        this.nnaMayor = nnaMayor;
    }
    public Boolean getNnaAdolescente() {
        return this.nnaAdolescente;
    }
    
    public void setNnaAdolescente(Boolean nnaAdolescente) {
        this.nnaAdolescente = nnaAdolescente;
    }
    public Boolean getNnaHermano() {
        return this.nnaHermano;
    }
    
    public void setNnaHermano(Boolean nnaHermano) {
        this.nnaHermano = nnaHermano;
    }
    public Set<Adoptante> getAdoptantes() {
        return this.adoptantes;
    }
    
    public void setAdoptantes(Set<Adoptante> adoptantes) {
        this.adoptantes = adoptantes;
    }
    public Set<ResidenteAct> getResidenteActs() {
        return this.residenteActs;
    }
    
    public void setResidenteActs(Set<ResidenteAct> residenteActs) {
        this.residenteActs = residenteActs;
    }
    public Set<HijoAct> getHijoActs() {
        return this.hijoActs;
    }
    
    public void setHijoActs(Set<HijoAct> hijoActs) {
        this.hijoActs = hijoActs;
    }




}


