package com.mimp.bean;
// Generated Dec 23, 2013 3:56:21 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InfoFamilia generated by hbm2java
 */
public class InfoFamilia implements java.io.Serializable {

    private long idinfoFamilia;
    private Familia familia;
    private String hojaReferencia;
    private String depRes;
    private String paisRes;
    private String domicilio;
    private String propiedadVivienda;
    private String tipoVivienda;
    private Long areaVivTotal;
    private Long areaVivConst;
    private String distVivienda;
    private Short luz;
    private Short agua;
    private Short desague;
    private String otrosServ;
    private String materConst;
    private String pared;
    private String techo;
    private String piso;
    private Character nivelSocioeconomico;
    private Short expectativaEdadMin;
    private String expectativaGenero;
    private String origenHijos;
    private Short puedeViajar;
    private String predisposicionAp;
    private String condicion;
    private String antecedenteFamilia;
    private Date fechaAntecedenteFamilia;
    private String observaciones;
    private Short nnaIncesto;
    private Short nnaMental;
    private Short nnaEpilepsia;
    private Short nnaAbuso;
    private Short nnaSifilis;
    private Short nnaSeguiMedico;
    private Short nnaOperacion;
    private Short nnaHiperactivo;
    private Short nnaEspecial;
    private Short nnaEnfermo;
    private Short nnaMayor;
    private Short nnaAdolescente;
    private Short nnaHermano;
    private String estadoCivil;
    private Date fechaMatrimonio;
    private String telefono;
    private Short expectativaEdadMax;
    private Set<ResidenteAct> residenteActs = new HashSet<ResidenteAct>(0);
    private Set<HijoAct> hijoActs = new HashSet<HijoAct>(0);
    private Set<Adoptante> adoptantes = new HashSet<Adoptante>(0);

    public InfoFamilia() {
    }

    public InfoFamilia(long idinfoFamilia, Familia familia) {
        this.idinfoFamilia = idinfoFamilia;
        this.familia = familia;
    }

    public InfoFamilia(long idinfoFamilia, Familia familia, String hojaReferencia, String depRes, String paisRes, String domicilio, String propiedadVivienda, String tipoVivienda, Long areaVivTotal, Long areaVivConst, String distVivienda, Short luz, Short agua, Short desague, String otrosServ, String materConst, String pared, String techo, String piso, Character nivelSocioeconomico, Short expectativaEdadMin, String expectativaGenero, String origenHijos, Short puedeViajar, String predisposicionAp, String condicion, String antecedenteFamilia, Date fechaAntecedenteFamilia, String observaciones, Short nnaIncesto, Short nnaMental, Short nnaEpilepsia, Short nnaAbuso, Short nnaSifilis, Short nnaSeguiMedico, Short nnaOperacion, Short nnaHiperactivo, Short nnaEspecial, Short nnaEnfermo, Short nnaMayor, Short nnaAdolescente, Short nnaHermano, String estadoCivil, Date fechaMatrimonio, String telefono, Short expectativaEdadMax, Set<ResidenteAct> residenteActs, Set<HijoAct> hijoActs, Set<Adoptante> adoptantes) {
        this.idinfoFamilia = idinfoFamilia;
        this.familia = familia;
        this.hojaReferencia = hojaReferencia;
        this.depRes = depRes;
        this.paisRes = paisRes;
        this.domicilio = domicilio;
        this.propiedadVivienda = propiedadVivienda;
        this.tipoVivienda = tipoVivienda;
        this.areaVivTotal = areaVivTotal;
        this.areaVivConst = areaVivConst;
        this.distVivienda = distVivienda;
        this.luz = luz;
        this.agua = agua;
        this.desague = desague;
        this.otrosServ = otrosServ;
        this.materConst = materConst;
        this.pared = pared;
        this.techo = techo;
        this.piso = piso;
        this.nivelSocioeconomico = nivelSocioeconomico;
        this.expectativaEdadMin = expectativaEdadMin;
        this.expectativaGenero = expectativaGenero;
        this.origenHijos = origenHijos;
        this.puedeViajar = puedeViajar;
        this.predisposicionAp = predisposicionAp;
        this.condicion = condicion;
        this.antecedenteFamilia = antecedenteFamilia;
        this.fechaAntecedenteFamilia = fechaAntecedenteFamilia;
        this.observaciones = observaciones;
        this.nnaIncesto = nnaIncesto;
        this.nnaMental = nnaMental;
        this.nnaEpilepsia = nnaEpilepsia;
        this.nnaAbuso = nnaAbuso;
        this.nnaSifilis = nnaSifilis;
        this.nnaSeguiMedico = nnaSeguiMedico;
        this.nnaOperacion = nnaOperacion;
        this.nnaHiperactivo = nnaHiperactivo;
        this.nnaEspecial = nnaEspecial;
        this.nnaEnfermo = nnaEnfermo;
        this.nnaMayor = nnaMayor;
        this.nnaAdolescente = nnaAdolescente;
        this.nnaHermano = nnaHermano;
        this.estadoCivil = estadoCivil;
        this.fechaMatrimonio = fechaMatrimonio;
        this.telefono = telefono;
        this.expectativaEdadMax = expectativaEdadMax;
        this.residenteActs = residenteActs;
        this.hijoActs = hijoActs;
        this.adoptantes = adoptantes;
    }

    public long getIdinfoFamilia() {
        return this.idinfoFamilia;
    }

    public void setIdinfoFamilia(long idinfoFamilia) {
        this.idinfoFamilia = idinfoFamilia;
    }

    public Familia getFamilia() {
        return this.familia;
    }

    public void setFamilia(Familia familia) {
        this.familia = familia;
    }

    public String getHojaReferencia() {
        return this.hojaReferencia;
    }

    public void setHojaReferencia(String hojaReferencia) {
        this.hojaReferencia = hojaReferencia;
    }

    public String getDepRes() {
        return this.depRes;
    }

    public void setDepRes(String depRes) {
        this.depRes = depRes;
    }

    public String getPaisRes() {
        return this.paisRes;
    }

    public void setPaisRes(String paisRes) {
        this.paisRes = paisRes;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public String getPropiedadVivienda() {
        return this.propiedadVivienda;
    }

    public void setPropiedadVivienda(String propiedadVivienda) {
        this.propiedadVivienda = propiedadVivienda;
    }

    public String getTipoVivienda() {
        return this.tipoVivienda;
    }

    public void setTipoVivienda(String tipoVivienda) {
        this.tipoVivienda = tipoVivienda;
    }

    public Long getAreaVivTotal() {
        return this.areaVivTotal;
    }

    public void setAreaVivTotal(Long areaVivTotal) {
        this.areaVivTotal = areaVivTotal;
    }

    public Long getAreaVivConst() {
        return this.areaVivConst;
    }

    public void setAreaVivConst(Long areaVivConst) {
        this.areaVivConst = areaVivConst;
    }

    public String getDistVivienda() {
        return this.distVivienda;
    }

    public void setDistVivienda(String distVivienda) {
        this.distVivienda = distVivienda;
    }

    public Short getLuz() {
        return this.luz;
    }

    public void setLuz(Short luz) {
        this.luz = luz;
    }

    public Short getAgua() {
        return this.agua;
    }

    public void setAgua(Short agua) {
        this.agua = agua;
    }

    public Short getDesague() {
        return this.desague;
    }

    public void setDesague(Short desague) {
        this.desague = desague;
    }

    public String getOtrosServ() {
        return this.otrosServ;
    }

    public void setOtrosServ(String otrosServ) {
        this.otrosServ = otrosServ;
    }

    public String getMaterConst() {
        return this.materConst;
    }

    public void setMaterConst(String materConst) {
        this.materConst = materConst;
    }

    public String getPared() {
        return this.pared;
    }

    public void setPared(String pared) {
        this.pared = pared;
    }

    public String getTecho() {
        return this.techo;
    }

    public void setTecho(String techo) {
        this.techo = techo;
    }

    public String getPiso() {
        return this.piso;
    }

    public void setPiso(String piso) {
        this.piso = piso;
    }

    public Character getNivelSocioeconomico() {
        return this.nivelSocioeconomico;
    }

    public void setNivelSocioeconomico(Character nivelSocioeconomico) {
        this.nivelSocioeconomico = nivelSocioeconomico;
    }

    public Short getExpectativaEdadMin() {
        return this.expectativaEdadMin;
    }

    public void setExpectativaEdadMin(Short expectativaEdadMin) {
        this.expectativaEdadMin = expectativaEdadMin;
    }

    public Short getExpectativaEdadMax() {
        return this.expectativaEdadMax;
    }

    public void setExpectativaEdadMax(Short expectativaEdadMax) {
        this.expectativaEdadMax = expectativaEdadMax;
    }

    public String getExpectativaGenero() {
        return this.expectativaGenero;
    }

    public void setExpectativaGenero(String expectativaGenero) {
        this.expectativaGenero = expectativaGenero;
    }

    public String getOrigenHijos() {
        return this.origenHijos;
    }

    public void setOrigenHijos(String origenHijos) {
        this.origenHijos = origenHijos;
    }

    public Short getPuedeViajar() {
        return this.puedeViajar;
    }

    public void setPuedeViajar(Short puedeViajar) {
        this.puedeViajar = puedeViajar;
    }

    public String getPredisposicionAp() {
        return this.predisposicionAp;
    }

    public void setPredisposicionAp(String predisposicionAp) {
        this.predisposicionAp = predisposicionAp;
    }

    public String getCondicion() {
        return this.condicion;
    }

    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    public String getAntecedenteFamilia() {
        return this.antecedenteFamilia;
    }

    public void setAntecedenteFamilia(String antecedenteFamilia) {
        this.antecedenteFamilia = antecedenteFamilia;
    }

    public Date getFechaAntecedenteFamilia() {
        return this.fechaAntecedenteFamilia;
    }

    public void setFechaAntecedenteFamilia(Date fechaAntecedenteFamilia) {
        this.fechaAntecedenteFamilia = fechaAntecedenteFamilia;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public Short getNnaIncesto() {
        return this.nnaIncesto;
    }

    public void setNnaIncesto(Short nnaIncesto) {
        this.nnaIncesto = nnaIncesto;
    }

    public Short getNnaMental() {
        return this.nnaMental;
    }

    public void setNnaMental(Short nnaMental) {
        this.nnaMental = nnaMental;
    }

    public Short getNnaEpilepsia() {
        return this.nnaEpilepsia;
    }

    public void setNnaEpilepsia(Short nnaEpilepsia) {
        this.nnaEpilepsia = nnaEpilepsia;
    }

    public Short getNnaAbuso() {
        return this.nnaAbuso;
    }

    public void setNnaAbuso(Short nnaAbuso) {
        this.nnaAbuso = nnaAbuso;
    }

    public Short getNnaSifilis() {
        return this.nnaSifilis;
    }

    public void setNnaSifilis(Short nnaSifilis) {
        this.nnaSifilis = nnaSifilis;
    }

    public Short getNnaSeguiMedico() {
        return this.nnaSeguiMedico;
    }

    public void setNnaSeguiMedico(Short nnaSeguiMedico) {
        this.nnaSeguiMedico = nnaSeguiMedico;
    }

    public Short getNnaOperacion() {
        return this.nnaOperacion;
    }

    public void setNnaOperacion(Short nnaOperacion) {
        this.nnaOperacion = nnaOperacion;
    }

    public Short getNnaHiperactivo() {
        return this.nnaHiperactivo;
    }

    public void setNnaHiperactivo(Short nnaHiperactivo) {
        this.nnaHiperactivo = nnaHiperactivo;
    }

    public Short getNnaEspecial() {
        return this.nnaEspecial;
    }

    public void setNnaEspecial(Short nnaEspecial) {
        this.nnaEspecial = nnaEspecial;
    }

    public Short getNnaEnfermo() {
        return this.nnaEnfermo;
    }

    public void setNnaEnfermo(Short nnaEnfermo) {
        this.nnaEnfermo = nnaEnfermo;
    }

    public Short getNnaMayor() {
        return this.nnaMayor;
    }

    public void setNnaMayor(Short nnaMayor) {
        this.nnaMayor = nnaMayor;
    }

    public Short getNnaAdolescente() {
        return this.nnaAdolescente;
    }

    public void setNnaAdolescente(Short nnaAdolescente) {
        this.nnaAdolescente = nnaAdolescente;
    }

    public Short getNnaHermano() {
        return this.nnaHermano;
    }

    public void setNnaHermano(Short nnaHermano) {
        this.nnaHermano = nnaHermano;
    }

    public String getEstadoCivil() {
        return this.estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public Date getFechaMatrimonio() {
        return this.fechaMatrimonio;
    }

    public void setFechaMatrimonio(Date fechaMatrimonio) {
        this.fechaMatrimonio = fechaMatrimonio;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Set<ResidenteAct> getResidenteActs() {
        return this.residenteActs;
    }

    public void setResidenteActs(Set<ResidenteAct> residenteActs) {
        this.residenteActs = residenteActs;
    }

    public Set<HijoAct> getHijoActs() {
        return this.hijoActs;
    }

    public void setHijoActs(Set<HijoAct> hijoActs) {
        this.hijoActs = hijoActs;
    }

    public Set<Adoptante> getAdoptantes() {
        return this.adoptantes;
    }

    public void setAdoptantes(Set<Adoptante> adoptantes) {
        this.adoptantes = adoptantes;
    }

}
