package com.mimp.bean;
// Generated 10/12/2013 02:25:47 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer idlog;
     private Personal personal;
     private Date fecha;
     private String tipoReg;
     private String NReg;
     private String incidencia;

    public Log() {
    }

	
    public Log(Personal personal) {
        this.personal = personal;
    }
    public Log(Personal personal, Date fecha, String tipoReg, String NReg, String incidencia) {
       this.personal = personal;
       this.fecha = fecha;
       this.tipoReg = tipoReg;
       this.NReg = NReg;
       this.incidencia = incidencia;
    }
   
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoReg() {
        return this.tipoReg;
    }
    
    public void setTipoReg(String tipoReg) {
        this.tipoReg = tipoReg;
    }
    public String getNReg() {
        return this.NReg;
    }
    
    public void setNReg(String NReg) {
        this.NReg = NReg;
    }
    public String getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(String incidencia) {
        this.incidencia = incidencia;
    }




}


