package com.mimp.bean;
// Generated Dec 18, 2013 9:57:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nna generated by hbm2java
 */
public class Nna  implements java.io.Serializable {


     private long idnna;
     private Car car;
     private Juzgado juzgado;
     private String nombre;
     private String apellidoP;
     private String apellidoM;
     private String sexo;
     private Date fechaNacimiento;
     private Short edadAnhos;
     private Short edadMeses;
     private Short actaNacimiento;
     private String condicionSalud;
     private String departamentoNacimiento;
     private String provinciaNacimiento;
     private String distritoNacimiento;
     private String paisNacimiento;
     private String lugarNac;
     private Date fechaResolAbandono;
     private Date fechaResolConsentida;
     private String clasificacion;
     private Short incesto;
     private Short mental;
     private Short epilepsia;
     private Short abuso;
     private Short sifilis;
     private Short seguiMedico;
     private Short operacion;
     private Short hiperactivo;
     private Short especial;
     private Short enfermo;
     private Short mayor;
     private Short adolescente;
     private Short hermano;
     private Short nn;
     private Set<Designacion> designacions = new HashSet<Designacion>(0);
     private Set<Prioritario> prioritarios = new HashSet<Prioritario>(0);
     private Set<ExpedienteNna> expedienteNnas = new HashSet<ExpedienteNna>(0);
     private Set<EstudioCaso> estudioCasos = new HashSet<EstudioCaso>(0);

    public Nna() {
    }

	
    public Nna(long idnna, Car car, Juzgado juzgado) {
        this.idnna = idnna;
        this.car = car;
        this.juzgado = juzgado;
    }
    public Nna(long idnna, Car car, Juzgado juzgado, String nombre, String apellidoP, String apellidoM, String sexo, Date fechaNacimiento, Short edadAnhos, Short edadMeses, Short actaNacimiento, String condicionSalud, String departamentoNacimiento, String provinciaNacimiento, String distritoNacimiento, String paisNacimiento, String lugarNac, Date fechaResolAbandono, Date fechaResolConsentida, String clasificacion, Short incesto, Short mental, Short epilepsia, Short abuso, Short sifilis, Short seguiMedico, Short operacion, Short hiperactivo, Short especial, Short enfermo, Short mayor, Short adolescente, Short hermano, Short nn, Set<Designacion> designacions, Set<Prioritario> prioritarios, Set<ExpedienteNna> expedienteNnas, Set<EstudioCaso> estudioCasos) {
       this.idnna = idnna;
       this.car = car;
       this.juzgado = juzgado;
       this.nombre = nombre;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.edadAnhos = edadAnhos;
       this.edadMeses = edadMeses;
       this.actaNacimiento = actaNacimiento;
       this.condicionSalud = condicionSalud;
       this.departamentoNacimiento = departamentoNacimiento;
       this.provinciaNacimiento = provinciaNacimiento;
       this.distritoNacimiento = distritoNacimiento;
       this.paisNacimiento = paisNacimiento;
       this.lugarNac = lugarNac;
       this.fechaResolAbandono = fechaResolAbandono;
       this.fechaResolConsentida = fechaResolConsentida;
       this.clasificacion = clasificacion;
       this.incesto = incesto;
       this.mental = mental;
       this.epilepsia = epilepsia;
       this.abuso = abuso;
       this.sifilis = sifilis;
       this.seguiMedico = seguiMedico;
       this.operacion = operacion;
       this.hiperactivo = hiperactivo;
       this.especial = especial;
       this.enfermo = enfermo;
       this.mayor = mayor;
       this.adolescente = adolescente;
       this.hermano = hermano;
       this.nn = nn;
       this.designacions = designacions;
       this.prioritarios = prioritarios;
       this.expedienteNnas = expedienteNnas;
       this.estudioCasos = estudioCasos;
    }
   
    public long getIdnna() {
        return this.idnna;
    }
    
    public void setIdnna(long idnna) {
        this.idnna = idnna;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public Juzgado getJuzgado() {
        return this.juzgado;
    }
    
    public void setJuzgado(Juzgado juzgado) {
        this.juzgado = juzgado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Short getEdadAnhos() {
        return this.edadAnhos;
    }
    
    public void setEdadAnhos(Short edadAnhos) {
        this.edadAnhos = edadAnhos;
    }
    public Short getEdadMeses() {
        return this.edadMeses;
    }
    
    public void setEdadMeses(Short edadMeses) {
        this.edadMeses = edadMeses;
    }
    public Short getActaNacimiento() {
        return this.actaNacimiento;
    }
    
    public void setActaNacimiento(Short actaNacimiento) {
        this.actaNacimiento = actaNacimiento;
    }
    public String getCondicionSalud() {
        return this.condicionSalud;
    }
    
    public void setCondicionSalud(String condicionSalud) {
        this.condicionSalud = condicionSalud;
    }
    public String getDepartamentoNacimiento() {
        return this.departamentoNacimiento;
    }
    
    public void setDepartamentoNacimiento(String departamentoNacimiento) {
        this.departamentoNacimiento = departamentoNacimiento;
    }
    public String getProvinciaNacimiento() {
        return this.provinciaNacimiento;
    }
    
    public void setProvinciaNacimiento(String provinciaNacimiento) {
        this.provinciaNacimiento = provinciaNacimiento;
    }
    public String getDistritoNacimiento() {
        return this.distritoNacimiento;
    }
    
    public void setDistritoNacimiento(String distritoNacimiento) {
        this.distritoNacimiento = distritoNacimiento;
    }
    public String getPaisNacimiento() {
        return this.paisNacimiento;
    }
    
    public void setPaisNacimiento(String paisNacimiento) {
        this.paisNacimiento = paisNacimiento;
    }
    public String getLugarNac() {
        return this.lugarNac;
    }
    
    public void setLugarNac(String lugarNac) {
        this.lugarNac = lugarNac;
    }
    public Date getFechaResolAbandono() {
        return this.fechaResolAbandono;
    }
    
    public void setFechaResolAbandono(Date fechaResolAbandono) {
        this.fechaResolAbandono = fechaResolAbandono;
    }
    public Date getFechaResolConsentida() {
        return this.fechaResolConsentida;
    }
    
    public void setFechaResolConsentida(Date fechaResolConsentida) {
        this.fechaResolConsentida = fechaResolConsentida;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Short getIncesto() {
        return this.incesto;
    }
    
    public void setIncesto(Short incesto) {
        this.incesto = incesto;
    }
    public Short getMental() {
        return this.mental;
    }
    
    public void setMental(Short mental) {
        this.mental = mental;
    }
    public Short getEpilepsia() {
        return this.epilepsia;
    }
    
    public void setEpilepsia(Short epilepsia) {
        this.epilepsia = epilepsia;
    }
    public Short getAbuso() {
        return this.abuso;
    }
    
    public void setAbuso(Short abuso) {
        this.abuso = abuso;
    }
    public Short getSifilis() {
        return this.sifilis;
    }
    
    public void setSifilis(Short sifilis) {
        this.sifilis = sifilis;
    }
    public Short getSeguiMedico() {
        return this.seguiMedico;
    }
    
    public void setSeguiMedico(Short seguiMedico) {
        this.seguiMedico = seguiMedico;
    }
    public Short getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Short operacion) {
        this.operacion = operacion;
    }
    public Short getHiperactivo() {
        return this.hiperactivo;
    }
    
    public void setHiperactivo(Short hiperactivo) {
        this.hiperactivo = hiperactivo;
    }
    public Short getEspecial() {
        return this.especial;
    }
    
    public void setEspecial(Short especial) {
        this.especial = especial;
    }
    public Short getEnfermo() {
        return this.enfermo;
    }
    
    public void setEnfermo(Short enfermo) {
        this.enfermo = enfermo;
    }
    public Short getMayor() {
        return this.mayor;
    }
    
    public void setMayor(Short mayor) {
        this.mayor = mayor;
    }
    public Short getAdolescente() {
        return this.adolescente;
    }
    
    public void setAdolescente(Short adolescente) {
        this.adolescente = adolescente;
    }
    public Short getHermano() {
        return this.hermano;
    }
    
    public void setHermano(Short hermano) {
        this.hermano = hermano;
    }
    public Short getNn() {
        return this.nn;
    }
    
    public void setNn(Short nn) {
        this.nn = nn;
    }
    public Set<Designacion> getDesignacions() {
        return this.designacions;
    }
    
    public void setDesignacions(Set<Designacion> designacions) {
        this.designacions = designacions;
    }
    public Set<Prioritario> getPrioritarios() {
        return this.prioritarios;
    }
    
    public void setPrioritarios(Set<Prioritario> prioritarios) {
        this.prioritarios = prioritarios;
    }
    public Set<ExpedienteNna> getExpedienteNnas() {
        return this.expedienteNnas;
    }
    
    public void setExpedienteNnas(Set<ExpedienteNna> expedienteNnas) {
        this.expedienteNnas = expedienteNnas;
    }
    public Set<EstudioCaso> getEstudioCasos() {
        return this.estudioCasos;
    }
    
    public void setEstudioCasos(Set<EstudioCaso> estudioCasos) {
        this.estudioCasos = estudioCasos;
    }




}


