package com.mimp.bean;
// Generated 5/12/2013 05:37:51 PM by Hibernate Tools 3.6.0



/**
 * Organismo generated by hbm2java
 */
public class Organismo  implements java.io.Serializable {


     private Integer idorganismo;
     private Representante representante;
     private Entidad entidad;
     private String competencia;

    public Organismo() {
    }

	
    public Organismo(Representante representante, Entidad entidad) {
        this.representante = representante;
        this.entidad = entidad;
    }
    public Organismo(Representante representante, Entidad entidad, String competencia) {
       this.representante = representante;
       this.entidad = entidad;
       this.competencia = competencia;
    }
   
    public Integer getIdorganismo() {
        return this.idorganismo;
    }
    
    public void setIdorganismo(Integer idorganismo) {
        this.idorganismo = idorganismo;
    }
    public Representante getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(Representante representante) {
        this.representante = representante;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(String competencia) {
        this.competencia = competencia;
    }




}


