package com.mimp.bean;
// Generated Dec 18, 2013 9:57:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Organismo generated by hbm2java
 */
public class Organismo  implements java.io.Serializable {


     private long idorganismo;
     private Entidad entidad;
     private String competencia;
     private Set<Representante> representantes = new HashSet<Representante>(0);

    public Organismo() {
    }

	
    public Organismo(long idorganismo, Entidad entidad) {
        this.idorganismo = idorganismo;
        this.entidad = entidad;
    }
    public Organismo(long idorganismo, Entidad entidad, String competencia, Set<Representante> representantes) {
       this.idorganismo = idorganismo;
       this.entidad = entidad;
       this.competencia = competencia;
       this.representantes = representantes;
    }
   
    public long getIdorganismo() {
        return this.idorganismo;
    }
    
    public void setIdorganismo(long idorganismo) {
        this.idorganismo = idorganismo;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(String competencia) {
        this.competencia = competencia;
    }
    public Set<Representante> getRepresentantes() {
        return this.representantes;
    }
    
    public void setRepresentantes(Set<Representante> representantes) {
        this.representantes = representantes;
    }




}


