package com.mimp.bean;
// Generated 10/12/2013 03:07:34 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Resolucion generated by hbm2java
 */
public class Resolucion  implements java.io.Serializable {


     private Integer idresolucion;
     private Evaluacion evaluacion;
     private String tipo;
     private String numero;
     private Date fechaResol;
     private Date fechaNotificacion;

    public Resolucion() {
    }

	
    public Resolucion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Resolucion(Evaluacion evaluacion, String tipo, String numero, Date fechaResol, Date fechaNotificacion) {
       this.evaluacion = evaluacion;
       this.tipo = tipo;
       this.numero = numero;
       this.fechaResol = fechaResol;
       this.fechaNotificacion = fechaNotificacion;
    }
   
    public Integer getIdresolucion() {
        return this.idresolucion;
    }
    
    public void setIdresolucion(Integer idresolucion) {
        this.idresolucion = idresolucion;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Date getFechaResol() {
        return this.fechaResol;
    }
    
    public void setFechaResol(Date fechaResol) {
        this.fechaResol = fechaResol;
    }
    public Date getFechaNotificacion() {
        return this.fechaNotificacion;
    }
    
    public void setFechaNotificacion(Date fechaNotificacion) {
        this.fechaNotificacion = fechaNotificacion;
    }




}


