package com.mimp.bean;
// Generated Nov 22, 2013 4:14:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Resolucion generated by hbm2java
 */
public class Resolucion  implements java.io.Serializable {


     private Integer idresolucion;
     private ExpedienteFamilia expedienteFamilia;
     private String tipo;
     private String numero;
     private Date fechaResol;
     private Date fechaNotificacion;

    public Resolucion() {
    }

	
    public Resolucion(ExpedienteFamilia expedienteFamilia) {
        this.expedienteFamilia = expedienteFamilia;
    }
    public Resolucion(ExpedienteFamilia expedienteFamilia, String tipo, String numero, Date fechaResol, Date fechaNotificacion) {
       this.expedienteFamilia = expedienteFamilia;
       this.tipo = tipo;
       this.numero = numero;
       this.fechaResol = fechaResol;
       this.fechaNotificacion = fechaNotificacion;
    }
   
    public Integer getIdresolucion() {
        return this.idresolucion;
    }
    
    public void setIdresolucion(Integer idresolucion) {
        this.idresolucion = idresolucion;
    }
    public ExpedienteFamilia getExpedienteFamilia() {
        return this.expedienteFamilia;
    }
    
    public void setExpedienteFamilia(ExpedienteFamilia expedienteFamilia) {
        this.expedienteFamilia = expedienteFamilia;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Date getFechaResol() {
        return this.fechaResol;
    }
    
    public void setFechaResol(Date fechaResol) {
        this.fechaResol = fechaResol;
    }
    public Date getFechaNotificacion() {
        return this.fechaNotificacion;
    }
    
    public void setFechaNotificacion(Date fechaNotificacion) {
        this.fechaNotificacion = fechaNotificacion;
    }




}


