package com.mimp.bean;
// Generated Dec 18, 2013 9:57:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reunion generated by hbm2java
 */
public class Reunion  implements java.io.Serializable {


     private long idreunion;
     private Turno2 turno2;
     private Date fecha;
     private String hora;
     private String duracion;
     private String direccion;
     private Short identificador;
     private String facilitador;
     private Short capacidad;
     private Short asistencia;
     private Set<AsistenciaFR> asistenciaFRs = new HashSet<AsistenciaFR>(0);

    public Reunion() {
    }

	
    public Reunion(long idreunion, Turno2 turno2) {
        this.idreunion = idreunion;
        this.turno2 = turno2;
    }
    public Reunion(long idreunion, Turno2 turno2, Date fecha, String hora, String duracion, String direccion, Short identificador, String facilitador, Short capacidad, Short asistencia, Set<AsistenciaFR> asistenciaFRs) {
       this.idreunion = idreunion;
       this.turno2 = turno2;
       this.fecha = fecha;
       this.hora = hora;
       this.duracion = duracion;
       this.direccion = direccion;
       this.identificador = identificador;
       this.facilitador = facilitador;
       this.capacidad = capacidad;
       this.asistencia = asistencia;
       this.asistenciaFRs = asistenciaFRs;
    }
   
    public long getIdreunion() {
        return this.idreunion;
    }
    
    public void setIdreunion(long idreunion) {
        this.idreunion = idreunion;
    }
    public Turno2 getTurno2() {
        return this.turno2;
    }
    
    public void setTurno2(Turno2 turno2) {
        this.turno2 = turno2;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Short getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(Short identificador) {
        this.identificador = identificador;
    }
    public String getFacilitador() {
        return this.facilitador;
    }
    
    public void setFacilitador(String facilitador) {
        this.facilitador = facilitador;
    }
    public Short getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Short capacidad) {
        this.capacidad = capacidad;
    }
    public Short getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Short asistencia) {
        this.asistencia = asistencia;
    }
    public Set<AsistenciaFR> getAsistenciaFRs() {
        return this.asistenciaFRs;
    }
    
    public void setAsistenciaFRs(Set<AsistenciaFR> asistenciaFRs) {
        this.asistenciaFRs = asistenciaFRs;
    }




}


