package com.mimp.bean;
// Generated Dec 23, 2013 10:39:27 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private long idsesion;
     private String NSesion;
     private Short habilitado;
     private Date fecha;
     private String hora;
     private String direccion;
     private String duracion;
     private String facilitador;
     private Short asistencia;
     private String unidad;
     private Set<FormularioSesion> formularioSesions = new HashSet<FormularioSesion>(0);
     private Set<Turno> turnos = new HashSet<Turno>(0);

    public Sesion() {
    }

	
    public Sesion(long idsesion) {
        this.idsesion = idsesion;
    }
    public Sesion(long idsesion, String NSesion, Short habilitado, Date fecha, String hora, String direccion, String duracion, String facilitador, Short asistencia, String unidad, Set<FormularioSesion> formularioSesions, Set<Turno> turnos) {
       this.idsesion = idsesion;
       this.NSesion = NSesion;
       this.habilitado = habilitado;
       this.fecha = fecha;
       this.hora = hora;
       this.direccion = direccion;
       this.duracion = duracion;
       this.facilitador = facilitador;
       this.asistencia = asistencia;
       this.unidad = unidad;
       this.formularioSesions = formularioSesions;
       this.turnos = turnos;
    }
   
    public long getIdsesion() {
        return this.idsesion;
    }
    
    public void setIdsesion(long idsesion) {
        this.idsesion = idsesion;
    }
    public String getNSesion() {
        return this.NSesion;
    }
    
    public void setNSesion(String NSesion) {
        this.NSesion = NSesion;
    }
    public Short getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Short habilitado) {
        this.habilitado = habilitado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getFacilitador() {
        return this.facilitador;
    }
    
    public void setFacilitador(String facilitador) {
        this.facilitador = facilitador;
    }
    public Short getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Short asistencia) {
        this.asistencia = asistencia;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Set<FormularioSesion> getFormularioSesions() {
        return this.formularioSesions;
    }
    
    public void setFormularioSesions(Set<FormularioSesion> formularioSesions) {
        this.formularioSesions = formularioSesions;
    }
    public Set<Turno> getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Set<Turno> turnos) {
        this.turnos = turnos;
    }




}


