package com.mimp.bean;
// Generated Dec 18, 2013 9:57:16 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private long idturno;
     private Sesion sesion;
     private Serializable inicioInscripcion;
     private Serializable finInscripcion;
     private Short vacantes;
     private Set<AsistenciaFT> asistenciaFTs = new HashSet<AsistenciaFT>(0);

    public Turno() {
    }

	
    public Turno(long idturno, Sesion sesion) {
        this.idturno = idturno;
        this.sesion = sesion;
    }
    public Turno(long idturno, Sesion sesion, Serializable inicioInscripcion, Serializable finInscripcion, Short vacantes, Set<AsistenciaFT> asistenciaFTs) {
       this.idturno = idturno;
       this.sesion = sesion;
       this.inicioInscripcion = inicioInscripcion;
       this.finInscripcion = finInscripcion;
       this.vacantes = vacantes;
       this.asistenciaFTs = asistenciaFTs;
    }
   
    public long getIdturno() {
        return this.idturno;
    }
    
    public void setIdturno(long idturno) {
        this.idturno = idturno;
    }
    public Sesion getSesion() {
        return this.sesion;
    }
    
    public void setSesion(Sesion sesion) {
        this.sesion = sesion;
    }
    public Serializable getInicioInscripcion() {
        return this.inicioInscripcion;
    }
    
    public void setInicioInscripcion(Serializable inicioInscripcion) {
        this.inicioInscripcion = inicioInscripcion;
    }
    public Serializable getFinInscripcion() {
        return this.finInscripcion;
    }
    
    public void setFinInscripcion(Serializable finInscripcion) {
        this.finInscripcion = finInscripcion;
    }
    public Short getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Short vacantes) {
        this.vacantes = vacantes;
    }
    public Set<AsistenciaFT> getAsistenciaFTs() {
        return this.asistenciaFTs;
    }
    
    public void setAsistenciaFTs(Set<AsistenciaFT> asistenciaFTs) {
        this.asistenciaFTs = asistenciaFTs;
    }




}


